### ISSUE TITLE
Agent Builder install dependencies.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#1061]
**Is your feature request related to a problem? Please describe.**
Currently I have to install all the dependencies that are listed in the skills manually.

**Describe the solution you'd like**
The agent builder would be good to run the `aea install` command on the background.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by DavidMinarsch** [comment]
This can be easily implemented by extending the AEABuilder and MultiAgentManager with a functionality to call the install helpers from cli
