### ISSUE TITLE
Unexpected skill de-registration behaviour

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1095]
**Is your feature request related to a problem? Please describe.**
If a skill is deregistered during initialization of one of its modules, it can lead to unexpected behaviour.

**Describe the solution you'd like**
Resolve below:
<img width="654" alt="Screenshot 2020-04-11 at 10 50 12" src="https://user-images.githubusercontent.com/19314578/79040715-68d77f00-7be2-11ea-8a2d-45a89a65c67b.png">

**Comment by marcofavorito** [comment]
@DavidMinarsch please could you provide instructions on how to reproduce the issue?
