### ISSUE TITLE
AEA eject functionality. 

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#1096]
**Describe the solution you'd like**

We could use a functionality similar to `npm eject` command to expose the AEA library and let the developer to modify the current instance of the library the way he wants. This will enable for example the developer to modify the Decision Maker the way he wants and eliminates the idea of having the DM as a package.

Not sure if this is fully applicable to the AEA framework needs more investigation.

**Comment by DavidMinarsch** [comment]
Modifying the library is already possible via editable installs of pip [see here](https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs). We will add some support to extend the DM soon!
