### ISSUE TITLE
Add code quality checks

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1110]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**

Add code quality checks like Codacy.

**Additional context**

Link: https://app.codacy.com/organizations

**Comment by DavidMinarsch** [comment]
Or this: https://github.com/codeclimate/codeclimate

**Comment by DavidMinarsch** [comment]
We added pylint; this will do for the time being.
