### ISSUE TITLE
Implement "aea search" based on string matching

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1116]
**Is your feature request related to a problem? Please describe.**

Currently, there's no obvious way to filter out results based on a string. A workaround is to do `aea search <package_type> | grep <string_query>`, but imho we could improve our tool without relying on external CLI tools.

For instance, if I wanted to find all the packages of a specific type whose ID has `oef` in their public ID, I could run:
```
aea search <package_type> oef
```

**Describe the solution you'd like**

Implement a string matching filter so that the output of `aea search` is already filtered.

**Describe alternatives you've considered**

Question: do we really need it? I think yes; the registry should definitely support a way to filter the results based on some constraints. It shouldn't be a job for the client for more efficient utilization of network resources.

**Additional context**

There is a lot of room for improvement: package type could be optional and be interpreted as just another constraint, support pattern matching with regexes, filtering by author etc.

Also, there should be control over the output of `aea search` (probably it should be treated as another issue). Instead of providing all the details by default (e.g. _description_), the default could be something like:
```
package_type,public_id_1
package_type,public_id_2
...
```

Many of the proposed changes might affect the registry APIs for searching.

**Comment by DavidMinarsch** [comment]
We already have this, e.g. `aea search connections --query oef`

**Comment by marcofavorito** [comment]
@DavidMinarsch what about the package type as an optional constraint?
