### ISSUE TITLE
Merge ComponentConfiguration into PackageConfiguration

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1120]
**Is your feature request related to a problem? Please describe.**

Question: is there a value in keeping `Component(Id|Configuration)` separate from `Package(Id|Configuration)`?

Remind that a component is-a package but excluding the case when the package is an agent. However, what about use only `Package`, and in all the case we need to treat it as a component, we raise error if it is instead an agent package?

**Describe the solution you'd like**

A method `Package.is_component()` that checks whether the package type is one of protocols, connections, contracts, and skills.
Also, in all the places where the code expects a component instead of a generic package, add the check.

**Describe alternatives you've considered**

**Additional context**

Maybe there's value in keeping them separated. Or there isn't value in applying the change; after all, it's just a minor refactoring.

**Comment by DavidMinarsch** [comment]
Closing. Not important enough to keep atm.
