### ISSUE TITLE
Transaction message initialization inconsistent

### ISSUE THREAD

**Issue by QibingLee** [fetchai/agents-aea#1137]
Hi, everyone. I met the following problems when I run the ml-model-trainer.
How can I solve it?

  File "vendor/fetchai/skills/ml_train/handlers.py", line 110, in _handle_terms
    info={"terms": terms, "counterparty_addr": ml_trade_msg.counterparty},
  File "/home/lqb/opt/anaconda3/envs/fetch/lib/python3.7/site-packages/aea/decision_maker/messages/transaction.py", line 94, in __init__
    assert self._is_consistent(), "Transaction message initialization inconsistent."

**Comment by DavidMinarsch** [comment]
Thanks @QibingLee. Looking into it now!

**Comment by QibingLee** [comment]
@DavidMinarsch    File "/home/lqb/opt/anaconda3/envs/fetch/lib/python3.7/site-packages/aea/decision_maker/messages/transaction.py", line 169, in tx_nonce
    assert self.is_set("tx_nonce"), "Tx_nonce is not set."
AssertionError: Tx_nonce is not set.

**Comment by QibingLee** [comment]
Errors occurred in   #assert isinstance(self.tx_nonce, str), "Tx_nonce must be of type str."
But I do not know why.

**Comment by DavidMinarsch** [comment]
The `aea/decision_maker/*` apis are under a lot of change currently. We forgot to update the skill. A fix is available here now: #1147
