### ISSUE TITLE
Investigate why unchanged protocols lead to different "outer" hashes

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1158]
In 0.3.1 we did not change any of the protocols. However, their hashes changed: https://github.com/fetchai/agents-aea/pull/1152/files#diff-16f080b2563a56a04f71fc5453a96630

Investigate what caused that and rectify.

**Comment by marcofavorito** [comment]
In looks like there was a problem in the computation of the outer hash before release `v0.3.1`. In fact, if the protocol package didn't change, the only reason for the outer hash to change is that the script that generates the hash is changed, namely the `scripts/generate_ipfs_hashes.py`.

However, either one of the two is right: the scripts at version `v0.3.0` or the same script at `v0.3.1`.

To solve the problem, I consider the CLI tool `ipfs` to be the tie-breaker.

Hence, to investigate the problem, I did the following:
- Be sure `ipfs` tool is installed locally (I used version `0.4.21`)
- `git checkout v0.3.0`
- `make clean`
- pick one of the protocols whose outer hash changed, i.e. `fetchai/default`.
In the specific case of `fetchai/default` protocol:
the older outer hash (`v0.3.0`) is: `Qme2skifJKoi2EpEM9CFnFZPM7LCzz7YF8muiiNNrxqJuA`
https://github.com/fetchai/agents-aea/blob/v0.3.0/packages/hashes.csv#L22
the newer outer hash (`v0.3.1`) is: `QmU5PttQevBHgignzFSgFHhE8viSsKBPThKxsXGx2mhQXx` https://github.com/fetchai/agents-aea/blob/v0.3.1/packages/hashes.csv#L28

- Run the CLI tool `ipfs` against the folder of the package. The command I used is:
```
ipfs add -r --only-hash aea/protocols/default
```
The flag `-r` is used to hash directories; the flag `--only-hash` makes the command to only chunk and hash - do not write to disk.

When I run the command on `v0.3.0` I get the following:
![image](https://user-images.githubusercontent.com/9467617/80956716-0731bb80-8e02-11ea-9bfe-0b2f038d2c5d.png)

The outer hash computed by `ipfs` is `QmU5PttQevBHgignzFSgFHhE8viSsKBPThKxsXGx2mhQXx`, which is different from `Qme2skifJKoi2EpEM9CFnFZPM7LCzz7YF8muiiNNrxqJuA`, and it's equal to the output of the script at `v0.3.1`.

The same for `fipa`:
![image](https://user-images.githubusercontent.com/9467617/80956968-88894e00-8e02-11ea-9f6c-4853ade2c825.png)
![image](https://user-images.githubusercontent.com/9467617/80956976-8c1cd500-8e02-11ea-9e21-3a0c780be193.png)

**Comment by marcofavorito** [comment]
Actually, there was another case we didn't consider: that the `hashes.csv` was outdated...

And in fact:
```
git checkout v0.3.0
python scripts/generate_ipfs_hashes.py
git diff
```

Gives:
![image](https://user-images.githubusercontent.com/9467617/80957324-3ac11580-8e03-11ea-8c01-5072a10b91b0.png)

**Comment by marcofavorito** [comment]
The `hashes.csv` at tag `v0.3.0` was not up to date.

Indeed:
```
git checkout v0.3.0
python scripts/generate_ipfs_hashes.py
git diff
```

Gives:
![image](https://user-images.githubusercontent.com/9467617/80957324-3ac11580-8e03-11ea-8c01-5072a10b91b0.png)
