### ISSUE TITLE
Add option `aea add --local <path-to-local-registry>`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1179]
**Is your feature request related to a problem? Please describe.**
In order to add a package from a custom local registry, the only way is to edit the field `registry_path` in the `aea-config.yaml` file.

**Describe the solution you'd like**
Add an option after `--local` to override the field in the `aea-config.yaml` file.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
`--registry-path` option was introduced a while back..
