### ISSUE TITLE
Wallet refactoring (split)

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1191]
**Is your feature request related to a problem? Please describe.**
- Currently, the wallet considers all keys to be used by the agent
- Some are used by connection; these should not be the same used for econ/finanical exchange

**Describe the solution you'd like**
- Allow for the wallet to be appropriately configured to have key-pairs for dm and key-pairs for connections.
- Extend loading mechanisms of connections accordingly

**Comment by marcofavorito** [comment]
We agreed on having an optional dictionary in `aea-config.yaml` with identifier `connection_private_key_paths` that will be exposed to some kind of "connection context" to each connection. Maybe `AgentContext` might fit the purpose.
