### ISSUE TITLE
Explore extensive usage of Plug-in architecture

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1229]
**Is your feature request related to a problem? Please describe.**
Some parts of the framework require easy extendability, as in most common open-source frameworks like Django, pytest, mkdocs etc.

However, we don't currently support very easily such paradigm.

**Describe the solution you'd like**
We could give the opportunity to the community to extend the `aea` framework by writing plug-ins.

I know that it's a very general statement. We should understand what to make extendible, how to make it possible and to what extents. Some more practical ideas:
- make easy for people to add their own `Crypto` implementations.
- add custom CLI commands (see e.g. https://github.com/django-extensions/django-extensions#installing-it)

For example, these can be declared in the `aea-config.yaml` file, under a section called `plugin: []` as it is done by MkDocs. Or, more interestingly, make them optionally pip-installable like Pytest plugins: https://docs.pytest.org/en/latest/writing_plugins.html#pip-installable-plugins.

Generally, draw inspiration from concepts like:
- Django apps: https://docs.djangoproject.com/en/3.0/ref/applications/
- Pytest plugin: https://docs.pytest.org/en/latest/writing_plugins.html
- Mkdocs plugin: https://www.mkdocs.org/user-guide/configuration/#plugins
- Markdown extensions: https://python-markdown.github.io/extensions/, https://python-markdown.github.io/extensions/api/
- OpenAI Gym: it lets you to `register(env_id)` your concrete subclass of `gym.Env` and instantiate it with `env_obj = make(env_id)`. This is usually done in the `__init__.py` of the PyPI package, but it can be done locally (as in Pytest): https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/__init__.py

**Describe alternatives you've considered**
n/a

**Additional context**
https://medium.com/omarelgabrys-blog/plug-in-architecture-dec207291800

**Comment by DavidMinarsch** [comment]
Related:
- supporting additional cryptos/ledger apis
- supporting additional scripts to be run alongside AEA
