### ISSUE TITLE
Add PUBLIC_ID object in each package

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1271]
**Is your feature request related to a problem? Please describe.**
The public id is only specified in yaml files.

**Describe the solution you'd like**
The public id must match the yaml and a check for this match must exist.

**Comment by marcofavorito** [comment]
Some ideas:

- *by convention*, there SHOULD be a `PUBLIC_ID` object in `__init__.py` of every package, and that must match the yaml. Problem: needs validation. And it requires a check at building time (or "add time" to the builder), Another script in the aea repository would help.

**Comment by DavidMinarsch** [comment]
I think we can do that straightforwardly as a convention now. Then when this becomes a requirement we can add some checks in the cli and registry (note; once its in registry fingerprints ensure that it cannot be changed)
