### ISSUE TITLE
Parse dependencies and install on `aea run`

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#128]
**Is your feature request related to a problem? Please describe.**
Currently the dependencies of packages have to be installed manually.

**Describe the solution you'd like**
We could auto install them on `aea run`.

**Describe alternatives you've considered**
We could also just parse the dependencies and ask the user to install them.

**Additional context**
-

**Comment by marcofavorito** [comment]
Depends on #96
