### ISSUE TITLE
Define abstract ComponentLoader and provide concrete implementations

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1291]
**Is your feature request related to a problem? Please describe.**

https://github.com/fetchai/agents-aea/pull/1280#issuecomment-634545008

**Describe the solution you'd like**
Implement such feature.

**Describe alternatives you've considered**
n/a

**Additional context**
Related to #1280 and #1290

**Comment by DavidMinarsch** [comment]
This was attempted and ultimately discarded in favour of the `reset` approach to the builder.
