### ISSUE TITLE
Extending packages is not straightforward

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1294]
**Is your feature request related to a problem? Please describe.**
Currently, when trying to extend a package in vendors, I need to manually copy it to the relevant package directory first.

**Describe the solution you'd like**
Provide a command which moves a package (say skill) from vendor to `skills`. Should work for all four package types.

Suggested behaviour:
`aea eject/move [package_type] [package_id]` will move a package (if present) from vendor to `package` dir. It will also update the author to the project author and set the version to the default version. It also will make the necessary updates in agent-config re package reference.

**Comment by marcofavorito** [comment]
Sounds good. However, instead of adding a new command, what about:
```
aea remove PACKAGE_TYPE PACKAGE_ID
aea add --no-vendor PACKAGE_TYPE PACKAGE_ID
```

notice the `--no-vendor`
