### ISSUE TITLE
Inconsistent hash computation for p2p_libp2p connection

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1302]
**Describe the bug**

After running the tests, the `fetchai/p2p_libp2p` connection generates the Go executable `libp2p_node` to work.

It is correctly declared to be ignored by the fingerprint computation. However, it seems it's not  ignored by the `generate_ipfs_hashes.py` script

**To Reproduce**

*TODO*

**Expected behavior**
n/a

**Screenshots**
n/a

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
This is caused by tests not cleaning up after themselves. The tests should not leave the binary in the p2p_libp2p directory.
