### ISSUE TITLE
Clarification on `go.sum` file in `p2p_libp2p`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1303]
**Is your feature request related to a problem? Please describe.**

From [here](https://github.com/fetchai/agents-aea/blob/master/packages/fetchai/connections/p2p_libp2p/connection.yaml#L16) I can see that `go.sum` is ignored in the fingerprint computation.

However, as stated [here](https://blog.golang.org/using-go-modules):
> Both go.mod and go.sum should be checked into version control.

I feel that one of the following is not ideal:
1. having `go.sum` in the version control
2. having `go.sum` in the fingerprint ignore pattern.

**Describe the solution you'd like**
I suppose the best is to include `go.sum` in the version control (1) AND remove it from the fingerprint ignore pattern (not 2). But maybe I am missing something.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
I agree with Marco's proposed solution.
