### ISSUE TITLE
Get rid of agent's liveness object

### ISSUE THREAD

**Issue by solarw** [fetchai/agents-aea#1323]
**Is your feature request related to a problem? Please describe.**
liveness object represents a limited set of agent states: started/stopped but actually there is a bigger amount of states that can be represented by the runtime
agent.state should be overviews and updated corresponding to runtime states.

tests and documentation should be updated accordingly 

**Describe the solution you'd like**
use runtime state as an agent state source: add several helpers methods like is_running, is_stopped is_connected for easy check of agent states.

**Describe alternatives you've considered**
probably stay liveness, but it will duplicate states and less flexible

**Comment by DavidMinarsch** [comment]
We decided to add five states to express the state an aea is in: “not_running”, “setting_up”, “running”, “tearing_down”, “failed”
