### ISSUE TITLE
OEFMessage serialisation/ deserialisation.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#145]
**Describe the bug**
When serialising an OEFMessage of type = OEF_ERROR it fails to deserialise it. The error code used to create the message is invalid.

**To Reproduce**
1.  Copy the following code :
```python
msg = OEFMessage(oef_type=OEFMessage.Type.OEF_ERROR, id=0, operation=OEFMessage.OEFErrorOperation.SEARCH_AGENTS)
msg_bytes = OEFSerializer().encode(msg)
deserialized_msg = OEFSerializer().decode(msg_bytes)
```

2. See error
  > ValueError: 'OEFErrorOperation.SEARCH_AGENTS' is not a valid OEFErrorOperation

**Expected behavior**
Generate the previously created msg

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs Mojave
 - Browser: N/A
 - Version: 10.14.6
**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by marcofavorito** [comment]
With version `0.1.6` the issue seem to be disappeared:
```python
from aea.protocols.oef.message import OEFMessage
from aea.protocols.oef.serialization import OEFSerializer

msg = OEFMessage(oef_type=OEFMessage.Type.OEF_ERROR, id=0, operation=OEFMessage.OEFErrorOperation.SEARCH_AGENTS)
msg_bytes = OEFSerializer().encode(msg)
deserialized_msg = OEFSerializer().decode(msg_bytes)

assert msg.get("operation") == OEFMessage.OEFErrorOperation.SEARCH_AGENTS
assert msg == deserialized_msg
```
```python
from aea.protocols.oef.message import OEFMessage
from aea.protocols.oef.serialization import OEFSerializer

msg = OEFMessage(oef_type=OEFMessage.Type.OEF_ERROR, id=0, operation=OEFMessage.OEFErrorOperation.SEARCH_AGENTS)
msg_bytes = OEFSerializer().encode(msg)
deserialized_msg = OEFSerializer().decode(msg_bytes)

assert msg.get("operation") == OEFMessage.OEFErrorOperation.SEARCH_AGENTS
assert msg == deserialized_msg
```
