### ISSUE TITLE
Contract loading to registry revision

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1459]
**Is your feature request related to a problem? Please describe.**
Currently, contracts are loaded into registry when `build` is called on the `AEABuilder`.

**Describe the solution you'd like**
Instead, load a contract during call to `from_config` method of `Contract` class. This means the method has one more side effect but it already has one. It also means we avoid code duplication and make it less likely that adding to registry is forgotten.

**Comment by marcofavorito** [comment]
@DavidMinarsch can you point us to the exact line for ` kwargs not processed in deploy transaction (ethereum)`?
