### ISSUE TITLE
Allow to explicitly declare behaviours that are registered programmatically.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#1480]
**Is your feature request related to a problem? Please describe.**
I am getting this warning message for an one shot behaviour that I want to register from then handler.
`Class DataUpdateBehaviour of type behaviours found but not declared in the configuration file ../packages/aris/skills/rail_receiver/behaviours.py.`

**Describe the solution you'd like**

I would like to have the option to declare the behaviour in the skill.yaml but to be able to call it when I want from code.

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by DavidMinarsch** [comment]
We could introduce a class var which can be toggled to avoid this.
