### ISSUE TITLE
Add agent name in logger path messages.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1568]
**Is your feature request related to a problem? Please describe.**

Currently, the agent name never appears in the logger paths. That prevents to configure logging per agent name. This could be particularly useful in many-agent-one-process setup.

**Describe the solution you'd like**
Add the agent name in the logger name. For instance, for a skill `skill_name` of author `author_name` belonging to an agent `agent_name` we could have:
```
aea.agent_name.skills.author_name.skill_name
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Is this the only way to do it? How about using the logging configuration options already provided and exposed in the asa-config.yaml?

**Comment by marcofavorito** [comment]
the problem is that the logger used should have the name mentioned above. In particular, `agent_name` should be set at runtime.
