### ISSUE TITLE
Avoid downloading already downloaded golang dependencies

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1618]
**Is your feature request related to a problem? Please describe.**
Whenever an AEA is started, it requires the step: `Downloading golang dependencies. This may take a while`.
Screenshot:
![image](https://user-images.githubusercontent.com/9467617/89533525-d8a5f100-d7f3-11ea-8095-ef2d5bb4f043.png)

**Describe the solution you'd like**
An easy check whether the dependencies have been already downloaded; or a more sophisticated check that takes into account the last time the AEA has been executed (the latter requires much more work, related to offline statefulness of the agent).
Also, we could consider to load them in a cache directory in `.aea`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Important but low priority item at the moment.
