### ISSUE TITLE
Weather station fails when the same client interacts with it twice

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1619]
**Describe the bug**

The weather station skill fails when the same AEA weather client starts a negotiation with the station. This happens only if the station has not been stopped between the first and the second request.

**To Reproduce**
1. run the weather demo once;
2. stop the weather client, and *don't stop* the weather station.
3. run the client again
4. See this error (at the top half):
![image](https://user-images.githubusercontent.com/9467617/89533888-68e43600-d7f4-11ea-9977-b49d3c2f28fb.png)

**Expected behavior**
the station behaves as in the first negotiation.

**Screenshots**
see above.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser n/a
 - Version: aea `0.5.3`

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
This is not a weather station specific issue. It is a result of the way dialogue references are currently built and verified. We will have to change this but a separate issue should be opened.

**Comment by DavidMinarsch** [comment]
@marcofavorito the problem here is that we use integers in the dialogue references and start counting from 0. We don't persist the count so on restart the agent starts counting up again. Instead, we can use a uuid and perhaps hash it as well.

**Comment by marcofavorito** [comment]
Yes I agree with the UUID or similar. It works like a nonce, a widely used technique.
