### ISSUE TITLE
Extra state in FIPA message

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#163]
**Is your feature request related to a problem? Please describe.**
No it is not related to a problem.

**Describe the solution you'd like**
Add one more state in FIPA message to exchange the data after both sides accept rather than loading a third protocol (default) to send the data.

**Comment by DavidMinarsch** [comment]
It appears that `inform` might be a somewhat matching performative (http://jmvidal.cse.sc.edu/library/XC00037H.pdf).
