### ISSUE TITLE
Multiple spawn with aea run

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#164]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Something like `aea run -10` would make it faster for development environment. The number after the dash could be the agents that the command is going to spawn.

**Comment by DavidMinarsch** [comment]
@Totoual what use case would this address?

**Comment by Totoual** [comment]
@DavidMinarsch it can help for testing and for multiple agent spawning for stress tests etc. ( I think it is something that will help the development. I cannot think of a real life scenario other than testing at this point.

**Comment by DavidMinarsch** [comment]
One could use it to spin up entire use cases

**Comment by DavidMinarsch** [comment]
I'd like some solution akin to:
1. `aea fetch [some_public_id]`
2. `aea fetch [another_public_id]`
3. `aea launch some_public_id, another_public_id`

So `aea launch` creates a subprocess and launches each project individually. It can accept `n` projects.

**Comment by DavidMinarsch** [comment]
Later, once https://github.com/fetchai/agents-aea/issues/607 is resolved, we can also allow for `aea launch some_public_id, another_public_id --threaded` or something like that.
