### ISSUE TITLE
Add autocompletion to `aea` cli tool

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1640]
**Is your feature request related to a problem? Please describe.**
The CLI tool `aea` lacks of autocompletion

**Describe the solution you'd like**
provide one.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Also:
- [ ] argument abbreviations
- [ ] flag to auto-add key on generation
