### ISSUE TITLE
Add abstract `Message` in `base.proto`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1641]
**Is your feature request related to a problem? Please describe.**

The spec `base.proto` is misaligned from class `aea.mail.base.Message` requirements. 

Specifically, the class `Message` has the field dialogue reference, the message id and the target fields. However, they are repeated in the definition of each `*.proto`, whereas those particular fields could be defined just once in the `base.proto`.

**Describe the solution you'd like**
Define a `Message` Protobuf message, and make all the messages of existing protocols to inherit from it.
For backward compatibility, it should still be possible to just send bytes in an `Envelope`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Try to use `extend` functionality of protobuf so we have a message class:
```
Message
    int32 message_id = 1;
    string dialogue_starter_reference = 2;
    string dialogue_responder_reference = 3;
    int32 target = 4;
```
and then the individual protocols' message classes extend this.
