### ISSUE TITLE
CLI functionality to generate multiaddress

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1657]
**Is your feature request related to a problem? Please describe.**
Currently, multi address is generated on go side, need it on python side too

**Describe the solution you'd like**
CLI functionality to generate multiaddress

**Comment by marcofavorito** [comment]
Reporting here the comment from: https://github.com/fetchai/agents-aea/pull/1695#discussion_r476244094

> As discussed, there are two ways this can be used, if called without connection_id, we simply load the private key from either private_key_paths or connection_private_key_paths (if flag provided), based on provided ledger_id and then compute the peer id using the multi address class.
> If the public id is provided, we first check if the package is present, then load the config from the connection specified, then use the config to retrieve host and port to construct the multi-address fully. You probably need another optional arg there to specify which field in config contains the url.
> We need this for the p2p_libp2p packages, so use them for orientation.
