### ISSUE TITLE
Add running agent configuration in a separate YAML object

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1670]
**Is your feature request related to a problem? Please describe.**
In `aea-config.yaml`, there are many fields related to parameters for the runtime performances of an AEA (e.g. runtime_mode, loop_mode etc.).

**Describe the solution you'd like**
Would be useful to have a specific object that contains all these parameters. I think it makes the AEA configuration more readable.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Whilst we won't separate these into individual files, at a code level we should implement the correct validations and separation of config and definition/meta-data.
