### ISSUE TITLE
Local node shows connection errors on sending or receiving

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1738]
**Is your feature request related to a problem? Please describe.**
When sending or receiving envelopes, the local node occasionally shows disconnection errors.
```
[agent119] Error in the sending loop: Connection is not connected! Connect first!
Exception in callback Future.set_result(True)
handle: <Handle Future.set_result(True)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
asyncio.exceptions.InvalidStateError: invalid state
```

**Describe the solution you'd like**
This can be investigated by running `run_benchmark.sh`.

We need to identify the issue and fix it to reliably run benchmarks.

**Comment by solarw** [comment]
it's a multiplexer's issue.  disconnect order. it disconnects connections first while send loop tries to use connection already disconnected.
