### ISSUE TITLE
Add script to check consistency between jsonschema and Python code

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1746]
**Is your feature request related to a problem? Please describe.**
Some code in the Python package could diverge from jsonschema files. E.g. differences between constants or regexes in Python code and the jsonschema definitions are not automatically detected.

**Describe the solution you'd like**
Write a script to detect divergence between the Python code and the jsonschema files.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
We did a manual check for v1
