### ISSUE TITLE
Support both `.yaml`. and `.yml`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1760]
**Is your feature request related to a problem? Please describe.**
Currently, the framework is tight to `.yaml` file extension, mostly for historical reasons. However, many other tools use `.yml` as extensions ([despite it's not the recommended one](https://yaml.org/faq.html))

**Describe the solution you'd like**
Allow the framework to be compliant with both of them; I'd give priority to `.yaml` which is both the first format the framework is used to and the official recommended file extension.

**Describe alternatives you've considered**

**Additional context**
Very very low priority.

**Comment by DavidMinarsch** [comment]
Benefit - cost analysis suggests this feature is not desirable.
