### ISSUE TITLE
When removing packages, detect unneeded dependencies

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1768]
**Is your feature request related to a problem? Please describe.**
After removing a package, we don't check whether its dependencies are still needed by some else package.

**Describe the solution you'd like**
Remove the unneeded dependencies automatically, or with a flag `--remove-deps`, or with a separate command like `aea update`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Not a fan of automatically removing dependencies. It should be an opt in functionality imo via a flag.
