### ISSUE TITLE
Add `aea upgrade` for agent project

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1769]
**Is your feature request related to a problem? Please describe.**
There is no easy way to update all the dependencies to the latest version.

**Describe the solution you'd like**
Use `aea update` to update all the dependencies of an aea project to the latest versions, while making sure the new combination of versions is still compatible.
Also, the command could check whether some dependencies are not needed anymore (see #1768)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Related to #1740
