### ISSUE TITLE
Add --sync flag to `generate-wealth` commands

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1773]
**Is your feature request related to a problem? Please describe.**
Currently, `aea generate-wealth` is asynchronous - it only sends the request of wealth generation through the ledger API. However, it doesn't wait until the transaction is confirmed.

**Describe the solution you'd like**
Add a `--sync` flag that waits until the transaction is not confirmed.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
`--sync` flag was added a while back.
