### ISSUE TITLE
Removing inner classes (especially in messages, dialogues)

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#1781]
**Issue**
Using nested classes in python is generally discouraged. We do this often across the framework. It also creates some unwanted dependencies (e.g. you cannot access fipa performative, unless you have a fipa message). 

**Solution**
Take inner classes out into independent classes in the same modules.

**Comment by DavidMinarsch** [comment]
The merit of the current approach is that importing the message class you get the performative "for free". There are certainly merits to extracting it but I don't think these are that big at the moment to warrant a code change.
