### ISSUE TITLE
Fetch Ledger Integration

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#180]
**Is your feature request related to a problem? Please describe.**
We cannot transact on the Fetch ledger at the moment.

**Describe the solution you'd like**
Integrate fetch ledger api into AEA framework.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Totoual** [comment]
I was able to change the crypto library to the ledger crypto library and generate public/private key. Haven't test yet though.
