### ISSUE TITLE
Make dotenv file configurable for an AEA project.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#1811]
**Is your feature request related to a problem? Please describe.**
Currently, the dot env file of an AEA project is not configurable.

See https://github.com/fetchai/agents-aea/pull/1810#discussion_r504054745 

**Describe the solution you'd like**
Make it configurable.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
The alternative is to just impose a preference order over `.env` files. E.g. `.env` > `.env.dev` etc..

**Comment by marcofavorito** [comment]
not considered a priority.
