### ISSUE TITLE
Auto release process

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#1854]
**Is your feature request related to a problem? Please describe.**
Our release process is close to being automated.

**Describe the solution you'd like**
Missing:
- [x] script to bump version of aea, and if necessary, bump version range for aea compatibility spec in yaml files
- [x] enable checks in CI for doc_links, generate_protocols, generate_api_docs [enable only when merging into master]
- [x] generate_all_protocols should auto detect protocols rather than have them hard coded; test protocols should also be regenerated from spec!
- [x] upgrade aea script needs to include auto updating of public ids for skills (i.e. init files of skills) 
- [x] api docs should auto detect if modules are not documented

**Comment by marcofavorito** [comment]
> upgrade aea script needs to include auto updating of public ids for skills (i.e. init files of skills)
