### ISSUE TITLE
Add block query to ledger_api protocol

### ISSUE THREAD

**Issue by jrriehl** [fetchai/agents-aea#1863]
**Is your feature request related to a problem? Please describe.**
I wrote a skill to query some data about a fetchai ledger block and then realized I need to do it again to get the ethereum block height. It occurred to me that this could be a common-enough issue that it is better suited for the ledger_api protocol since it really only involves a simple query.

**Describe the solution you'd like**
It would be great to send a message to the LedgerApi requesting the block height or other useful info and to receive the response as a return message.

**Describe alternatives you've considered**
For the fetchai ledger, we could simply do an http request to the ledger url (e.g. https://rpc-beacon-land.sandbox.fetch-ai.com/block), read the json response, and do an arbitrary query as a dict lookup.

For ethereum, we could implement a few of the most useful functions listed here: https://infura.io/docs/ethereum/json-rpc/eth-blockNumber.

**Comment by DavidMinarsch** [comment]
In the `ledger_api` protocol we could include two new performatives: `get_state` and `state`. They can look as follows in the spec:
```
  get_state:
    ledger_id: pt:str
    callable: pt:str
    kwargs: ct:Kwargs
  state:
    state: ct:State
```
This would then allow to execute arbitrary methods on the underlying ledger api.

**Comment by jrriehl** [comment]
There are analogous queries for getting the block in both [ethereum](https://web3js.readthedocs.io/en/v1.2.0/web3-eth.html#getblock) and [tendermint](https://docs.tendermint.com/master/rpc/#/Info/block) RPCs that cover all of the use cases that I had in mind. Were you thinking of more arbitrary queries than this?

**Comment by DavidMinarsch** [comment]
Yes I was thinking that the next person might want to query another ledger level (rather than contract level) variable. So rather than extending the protocol adhoc each time, I'd like to see a generic query for ledger level state which then gets executed using the underlying ledger api.
