### ISSUE TITLE
MAM: switch MultiAgentManager.add_project to local=False by default

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#1913]
**Is your feature request related to a problem? Please describe.**
IMO Registry fetch should be a priority so worth switching to it by default.

**Describe the solution you'd like**
Change a default value of arg.

**Comment by DavidMinarsch** [comment]
We now have a `mixed` mode. So we could point to that.

**Comment by DavidMinarsch** [comment]
Closing as either works
