### ISSUE TITLE
MAM: make MultiAgentManager.add_project to be able to add the same Agent with different alias

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#1914]
**Is your feature request related to a problem? Please describe.**
Currently you can't add an Agent with the same public_id twice with different alias. I think it's the case when user wants to have two similar agents used for different purposes.

**Describe the solution you'd like**
To make an alias a unique identifier.

**Comment by DavidMinarsch** [comment]
Already supported by default
