### ISSUE TITLE
Error: Key 'location' is not contained in the dictionary to update.

### ISSUE THREAD

**Issue by kskruegerkskrueger** [fetchai/agents-aea#1919]
Okay people...
I am a real total noob, so I hope this question is not too embarrassing or stupid:
I am trying to get an agent running for the testnet. I am not getting this issue resolved and I am not understanding where to look for proper "definition" of that key.

Any ideas would be of great help

**Comment by DavidMinarsch** [comment]
Hi @kskruegerkskrueger , thanks for your issue report. The problem here is that you don't get enough context to resolve the error. We are fixing this for `0.7.3` with this PR: #1917 . Should be on PyPI tomorrow.
