### ISSUE TITLE
aea.exceptions.AEAException: Raised <class 'ModuleNotFoundError'>(No module named 'packages.fetchai.skills.error.handlers')

### ISSUE THREAD

**Issue by ashnaeldho** [fetchai/agents-aea#1929]
Hi all,

I'm new to this AEA concept and was trying the demos mentioned in [the](https://fetch.ai/). When I tried to run the TAC skills [demo] (https://docs.fetch.ai/aea/tac-skills/), I'm getting the following error:

> Traceback (most recent call last):
 

>  File "/home/g2-test/.local/share/virtualenvs/github-repos-0NZ9BDfU/lib/python3.7/site-packages/aea/helpers/multiple_executor.py", line 210, in wait_future

> await future

>  File "/home/g2-test/.local/share/virtualenvs/github-repos-0NZ9BDfU/lib/python3.7/site-packages/aea/helpers/multiple_executor.py", line 210, in wait_future

> await future

> aea.exceptions.AEAException: Raised <class 'ModuleNotFoundError'>(No module named 'packages.fetchai.skills.error.handlers')

> info: Agent tac_controller terminated with exit code 1

> info: Agent tac_participant_one terminated with exit code 1

> info: Agent tac_participant_two terminated with exit code 1

I have followed exactly the same steps as mentioned in the link(tried creating the AEA using the scratch and automatic method). In both ways, I'm getting the same error. I was using Ubuntu 18.04. 
Kindly help me in solving this.

**Comment by DavidMinarsch** [comment]
Hi @ashnaeldho, thanks for the report. I was not able to replicate this yet. Can you give me more info on `aea --version` and which exact commands are failing?

**Comment by ashnaeldho** [comment]
Hi @DavidMinarsch ,
My aea --version is 0.7.2.

Following are the commands which I used:
To create TAC controller, open a new terminal and type:
`aea fetch fetchai/tac_controller:0.13.0
cd tac_controller
aea install
`
INorder to create TAC participants, open another terminal and type:
`aea fetch fetchai/tac_participant:0.15.0 --alias tac_participant_one
aea fetch fetchai/tac_participant:0.15.0 --alias tac_participant_two
cd tac_participant_two
aea install
cd tac_participant_one
aea install
`

Adding keys for all AEA's
In TAC controller terminal, type:
`aea generate-key fetchai
aea add-key fetchai fetchai_private_key.txt
aea add-key fetchai fetchai_private_key.txt --connection
`

In the second terminal for tac_participants, type:
`cd tac_participant_one
aea generate-key fetchai
aea add-key fetchai fetchai_private_key.txt
aea add-key fetchai fetchai_private_key.txt --connection`

For TAC_participant_two, type:
`cd tac_participant_two
aea generate-key fetchai
aea add-key fetchai fetchai_private_key.txt
aea add-key fetchai fetchai_private_key.txt --connection
`

Updating game parameters in the cotroller(in the tac_controller terminal),
`aea config get vendor.fetchai.skills.tac_control.models.parameters.args.registration_start_time
aea config set vendor.fetchai.skills.tac_control.models.parameters.args.registration_start_time '01 01 2020  00:01'
`

Ruuning the TAC controller
`aea run`

Once you see a message of the form To join its network use multiaddr: ['SOME_ADDRESS'] take note of the address.
Open connection.yaml in tac_participant_one -> vendor -> fetchai -> coonecttions -> p2p_libp2p-> connection.yaml and add the following there:
`config:
  delegate_uri: 127.0.0.1:11001
  entry_peers: ['SOME_ADDRESS']
  local_uri: 127.0.0.1:9001
  log_file: libp2p_node.log
  public_uri: 127.0.0.1:9001`


Similarly, Open connection.yaml in tac_participant_two -> vendor -> fetchai -> coonecttions -> p2p_libp2p-> connection.yaml and add the following there:
`config:
  delegate_uri: 127.0.0.1:11002
  entry_peers: ['SOME_ADDRESS']
  local_uri: 127.0.0.1:9002
  log_file: libp2p_node.log
  public_uri: 127.0.0.1:9002
`

where SOME_ADDRESS is replaced accordingly.

Open a new terminal and type:
`aea launch tac_controller tac_participant_one tac_participant_two`.

I'm getting the error when I try to do the last command(aea launch tac_controller tac_participant_one tac_participant_two).
