### ISSUE TITLE
aea push skill error

### ISSUE THREAD

**Issue by Matteo23647** [fetchai/agents-aea#1965]
when I did the step 7 ,it came out the "Error: Unable to read authentication config. Please sign in with "aea login" command."
screenshot is list down here:

 AEA 'xxxxxxxx' interrupted!
Stopping AEA 'xxxxxxxx' ...
[INFO]: [xxxxxxxx] unregistering service from SOEF.
[INFO]: [xxxxxxxx] unregistering agent from SOEF.
[INFO]: [xxxxxxxx] HTTP Client has shutdown on port: 8000.
AEA 'xxxxxxxx' stopped.
root@abcdefg:~/registration_aea_aw1/xxxxxxxx# aea get-wealth fetchai
100000000000000003000
root@abcdefg:~/registration_aea_aw1/xxxxxxxx# aea push skill xxxxxxxx/simple_seller:0.1.0
Error: Unable to read authentication config. Please sign in with "aea login" command.
root@abcdefg:~/registration_aea_aw1/xxxxxxxx# aea login
Usage: aea login [OPTIONS] USERNAME
Try 'aea login --help' for help.

Error: Missing argument 'USERNAME'.
root@abcdefg:~/registration_aea_aw1/xxxxxxxx# aea login 'xxxxxxxx'
Password:
Signing in as xxxxxxxx...
Error: {'non_field_errors': ['Unable to log in with provided credentials.']}
root@abcdefg:~/registration_aea_aw1/xxxxxxxx# aea login xxxxxxxx
Password:
Signing in as xxxxxxxx...
Error: {'non_field_errors': ['Unable to log in with provided credentials.']}

Expecting  solutions ASAP,for there is not too much time to finish the  AW-2.

Ubuntu  18.04.4  LTS

**Comment by DavidMinarsch** [comment]
This is not an error per-se with the CLI. The issue is caused by invalid credentials (password and user name combination). We improved the Server response to make it more explicit.
