### ISSUE TITLE
Improve AgentConfig.update method

### ISSUE THREAD

**Issue by solarw** [fetchai/agents-aea#1975]
**Is your feature request related to a problem? Please describe.**
AgentConfig.update method does not support all the fields

**Describe the solution you'd like**
make update method compatible with all fields supported in config

**Additional context**
MultiAgentManager uses it, but now implemented with workaround and dict patching instead of AgentConfig.update

**Comment by DavidMinarsch** [comment]
Only some fields are allowed to be editable.

We do need to improve config updating and make the programmatic usage more straightforward.
