### ISSUE TITLE
Module loading in tests

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#1983]
**Describe the bug**
When running pytests on specific tests in isolation (not running all tests such as in CI) that cover code with references to something under `packages.fetchai....`, module loading error occurs. 

Note: this might be a broader issue than tests to do with the order of modules and dependencies being loaded.

Example: Running any of the test methods under `tests/test_packages/test_skills/test_tac_negotiation/test_dialogues.py::TestDialogues`, which test methods of the `dialogue.py` module of the `tac_negotiation` skill (note this skill has code in `/packages/fetchai/skills/tac_negotiation/strategy.py` line 45 that imports from `packages.fetchai.contracts.erc1155.contract`), the following is the result:

```
test setup failed
cls = <class 'tests.test_packages.test_skills.test_tac_negotiation.test_transactions.TestTransactions'>

    @classmethod
    def setup(cls):
        """Setup the test class."""
>       super().setup()

/Users/ali/Projects/agents-aea/tests/test_packages/test_skills/test_tac_negotiation/test_transactions.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/ali/Projects/agents-aea/aea/test_tools/test_skill.py:449: in setup
    cls._skill = Skill.from_dir(str(cls.path_to_skill), agent_context)
/Users/ali/Projects/agents-aea/aea/skills/base.py:770: in from_dir
    return Skill.from_config(configuration, agent_context, **kwargs)
/Users/ali/Projects/agents-aea/aea/skills/base.py:819: in from_config
    str(directory / "handlers.py"), handlers_by_id, skill_context
/Users/ali/Projects/agents-aea/aea/skills/base.py:513: in parse_module
    handler_module = load_module("handlers", Path(path))
/Users/ali/Projects/agents-aea/aea/helpers/base.py:105: in load_module
    spec.loader.exec_module(module)  # type: ignore
<frozen importlib._bootstrap_external>:728: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
/Users/ali/Projects/agents-aea/packages/fetchai/skills/tac_negotiation/handlers.py:53: in <module>
    from packages.fetchai.skills.tac_negotiation.strategy import Strategy
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    """This module contains the abstract class defining an agent's strategy for the TAC."""
    
    import copy
    import random
    from enum import Enum
    from typing import Any, Dict, List, Optional, Tuple, cast
    
    from aea.common import Address
    from aea.decision_maker.default import OwnershipState, Preferences
    from aea.exceptions import enforce
    from aea.helpers.search.generic import (
        AGENT_LOCATION_MODEL,
        AGENT_REMOVE_SERVICE_MODEL,
        AGENT_SET_SERVICE_MODEL,
    )
    from aea.helpers.search.models import (
        Constraint,
        ConstraintType,
        Description,
        Location,
        Query,
    )
    from aea.helpers.transaction.base import Terms
    from aea.skills.base import Model
    
>   from packages.fetchai.contracts.erc1155.contract import PUBLIC_ID as CONTRACT_ID
E   ModuleNotFoundError: No module named 'packages.fetchai.contracts'; 'packages.fetchai' is not a package

/Users/ali/Projects/agents-aea/packages/fetchai/skills/tac_negotiation/strategy.py:45: ModuleNotFoundError

Assertion failed
```

**To Resolve it (a workaround)**
Add `from packages.fetchai.skills.tac_negotiation.behaviours import GoodsRegisterAndSearchBehaviour` (or in fact any class from any part of the `tac_negotiation` skill) to the above module, and then try running the test. The error should not be raised. Note, the test does not actually use this import, but somehow this helps with the module loading that is needed.

**To Reproduce**
Run any of the methods under `tests/test_packages/test_skills/test_tac_negotiation/test_dialogues.py::TestDialogues` using pytest.

**Expected behavior**
The test runs

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by DavidMinarsch** [comment]
I think the issue causing this is that the setup_class does not ensure we load all the skill dependencies. It needs to do the same as AEABuilder and first load all the skill dependencies and then the skill.
