### ISSUE TITLE
Transactions failed in case of 3 agents

### ISSUE THREAD

**Issue by hukka-mail-ru** [fetchai/agents-aea#1994]
**Describe the bug**
In case of 3 agents: the 1st transaction is OK, the other two are failed.

**To Reproduce**
- Start 3 agents (having generated keys for each of them). 
- Send a transaction towards each of the agents. 
- All the agents check the transaction against the ledger ( by calling LedgerApis.is_transaction_settled(), LedgerApis.is_transaction_valid() ) and reported "transaction confirmed". 
- Open https://explore-agent-land.fetch.ai/transactions and enter the transaction digests, one-by-one.

You can see: only the first transaction was OK, the other two were failed.

**Screenshots**
![scr](https://user-images.githubusercontent.com/17333385/100222061-9b907680-2f2a-11eb-85e6-b8fee5c909d6.png)

**Comment by DavidMinarsch** [comment]
Thank you for reporting. We fixed this in #2002. It will be available on the AEA registry as part of the next release.
