### ISSUE TITLE
AW3 Transaction Fails with `Unknown error: unauthorized: signature verification failed; verify correct account sequence and chain-id`

### ISSUE THREAD

**Issue by Dassy23** [fetchai/agents-aea#1998]
**Describe the bug**
Seller agent on AW3 is registered and created using https://docs.fetch.ai/i_nets/quickstart-aw1/. No test fet is deposited into account.
Seller agent is deployed as a mobility agent with the following strategy configs in the config.yaml 
      ```
      service_data:
        key: seller_service
        value: mobility_data
      service_id: mobility_data
      shared_state_key: mobility_data
      unit_price: 5  
      ```
Agent does not receive transaction but agent explorer shows error when buyer tries to send transaction to mobility agent.

**To Reproduce**
1. Register agent using  https://docs.fetch.ai/i_nets/quickstart-aw1/
2. Change aea-config.yaml to 
`
public_id: dassy23/simple_seller:0.1.0
type: skill
models:
  strategy:
    args:
      location:
        latitude: 52.52
        longitude: 13.405
      service_data:
        key: seller_service
        value: mobility_data
      service_id: mobility_data
      shared_state_key: mobility_data
      unit_price: 5
`
3. Add mobility url to aea-config.yaml

`
public_id: dassy23/simple_data_request:0.1.0
type: skill
behaviours:
  http_request:
    args:
      request_interval: 20
      body: ''
      method: get
      url: 'YOUR URL
handlers:
  http:
    args:
      shared_state_key: mobility_data
`
4. Run and wait for transaction.

**Expected behavior**
Transaction should be received by agent

**Screenshots**
<img width="988" alt="Screen Shot 2020-11-25 at 10 31 48 AM" src="https://user-images.githubusercontent.com/31330002/100271398-49d9f300-2f0e-11eb-879e-8583e1afdae1.png">

**Additional context**
<img width="1402" alt="Screen Shot 2020-11-25 at 11 09 21 AM" src="https://user-images.githubusercontent.com/31330002/100271666-b48b2e80-2f0e-11eb-9170-59ab92ce0b3d.png">

**Comment by DavidMinarsch** [comment]
Thanks @Dassy23 , this is a problem with our buyer agent. The PR #2002 fixes it. We will update the buyer agent asap.
