### ISSUE TITLE
Request for gas price adjustment by key

### ISSUE THREAD

**Issue by 8ball030** [fetchai/agents-aea#1999]
**Is your feature request related to a problem? Please describe.**
When running agents on the main ethereum net,

There is not a simple way to go ahead and set the gas price.

**Describe the solution you'd like**
It would really cool if there was a way to set the gas price by key.

I.e.

slow
medium
fast
ultrafast

**Describe alternatives you've considered**
Alternatively, I need to make a http call which introduces A) external dependancies and B) a http which can cause errors within t he rest of the application

**Additional context**

**Comment by DavidMinarsch** [comment]
We could add support for optionally configuring this on the ledger connection https://docs.ethgasstation.info/gas-price and then allowing for the key to be passed in the kwargs.
