### ISSUE TITLE
Add 'sender' field to 'Message' class

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#200]
**Is your feature request related to a problem? Please describe.**

Some parts of the code need the `Message` alongside the sender of that message, e.g. `handle(msg, sender)`

**Describe the solution you'd like**

Having a special property `sender` in the `Message` class.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by DavidMinarsch** [comment]
Expose as property and set framework side
