### ISSUE TITLE
Echo skill demo error

### ISSUE THREAD

**Issue by ashnaeldho** [fetchai/agents-aea#2055]
Hi all,

I was trying the echo skill demo.
In one terminal, I ran the aea using the command `aea run` and in the other terminal, I went to my_first_agent folder and wrote
`echo 'my_first_aea,sender_aea,fetchai/default:0.9.0,\x08\x01\x12\x011*\x07\n\x05hello,' >> input_file`,
it is showing the following error:

> info: [my_first_aea] Echo Behaviour: act method called.
>info: [my_first_aea] Echo Behaviour: act method called.
>info: [my_first_aea] Echo Behaviour: act method called.
>vendor/fetchai/protocols/default/serialization.py:89: RuntimeWarning: Unexpected end-group tag: Not all data was converted
>  message_pb.ParseFromString(obj)
>warning: [my_first_aea] Decoding error. Exception: 'None' is not a valid Performative
>warning: [my_first_aea] Decoding error for envelope: Envelope(to=my_first_aea, sender=sender_aea, >protocol_id=fetchai/default:0.9.0, message=b'\\x08\\x01\\x12\\x011*\\x07\\n\\x05hello'). Protocol_id='fetchai/default:0.9.0' and >message='b'\\x08\\x01\\x12\\x011*\\x07\\n\\x05hello'' are inconsistent.
>info: [my_first_aea] Echo Behaviour: act method called.
>info: [my_first_aea] Echo Behaviour: act method called. 

According to the video in the introduction, when I run this, it should save the message in input_file and output_file. But, for me, the input_file is empty and output_file has the following error.

> sender_aea,fetch1lplf9xttncpuzvff9qhh87vusvdtvx3ly0nx7f,fetchai/default:0.9.0,�*�2�
>Decoding error.u
>envelope>i3Jh&|UuJ1?b97%}WnmHub7gL1WpZC(Wnmf>W@U6^XklqDWMyVyb!>DxFfKVRFd`vbcrZ9zcrY<scrh|ucrY<BDqMIlH(YL9cr>Z0+Wo&G3

How can this be solved?

aea --version is 0.7.2
OS: Ubuntu 18.04

**Comment by DavidMinarsch** [comment]
Hi @ashnaeldho , thanks for pointing it out. We will fix it. In the meantime, I suggest using `aea interact` which let's you do the same thing (see Quickstart: https://docs.fetch.ai/aea/quickstart/)
