### ISSUE TITLE
`build_entrypoint` should be a shell command or script, not a Python script.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#2108]
**Is your feature request related to a problem? Please describe.**

Currently, the field `build_entrypoint` expects as value a path to a Python script. This is not ideal, as it tights the configuration to the Python ecosystem.

**Describe the solution you'd like**

Don't run `build_entrypoint` exclusively as a Python script, but as shell command/script.

**Describe alternatives you've considered**
n/a

**Additional context**

The script `packages/fetchai/connections/p2p_libp2p/connection.py` should have a Python shebang `#!/usr/bin/env python3`.

**Comment by DavidMinarsch** [comment]
@marcofavorito but the configuration IS tied to the Python AEA implementation. I can see an argument for both. The benefit of the Python script entry point is that we automatically can manage the run.
