### ISSUE TITLE
Package specifiers in component overrides not bumped

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#2116]
**Is your feature request related to a problem? Please describe.**
The doc `docs/multi-agent-manager.md` does contain a component override which does not get properly bumped when the version of the component is incremented.

**Describe the solution you'd like**
Fix

**Comment by marcofavorito** [comment]
Thanks for the issue. I suspect it's not related to component overrides, as the script is not actually aware of them when parsing docs. It's just that we don't match JSON objects of the form:
```
{
    "name": "p2p_libp2p",
    "author": "fetchai",
    "version": "0.13.0",
    "type": "connection",
    ...
}
```
