### ISSUE TITLE
Issues with TAC

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#2128]
**List of issues with TAC**
Note: These issues may not specifically be in the TAC code but in the core aea code, but they appear in TAC.

**Issue 1**:
**Problem**:	Incorrect `dialogue.str()`
**Detail**: 	The function just interleaves messages, while the order may not be as such.
**Solution**:	It must order and represent messages based on their ids.

**Issue 2**:
**Problem**:	Simultaneous message sending
**Detail**:	When two agents simultaneously send a message to each other, the order becomes corrupted.
**Example**:	Consider the following:

(agent) (sends/receives) (message_id, message) 
X sends (1, a)
Y receives (1, a)
Y sends (2, b)
X receives (2, b)
X sends (3, c)
Y sends (3, d)

At this point:

X’s dialogue: (1, a) —> (2, b) —> (3, c)
Y’s dialogue: (1, a) —> (2, b) —> (3, d)

Now:

X receives (3, d)
Y receives (3, c)

And both those messages are dropped because their message ids are incorrect with respect to the local dialogue structure the two agents hold.
**Solution**:...

**Comment by DavidMinarsch** [comment]
Message id's are only unique for the tuple `(sender, dialogue_ref)`. We need to account for this in the code base.
