### ISSUE TITLE
Add the ability to use default ledger for cert request

### ISSUE THREAD

**Issue by lrahmani** [fetchai/agents-aea#2131]
**Is your feature request related to a problem? Please describe.**
users have to make sure that cert request ledger id matches default one

**Describe the solution you'd like**
allow for a token to be set to `cert_request[i].ledger_id` such as `"default"`

**Describe alternatives you've considered**
No

**Additional context**
Not applicable

**Comment by DavidMinarsch** [comment]
I worry the cost of maintaining this is higher than the benefit.
