### ISSUE TITLE
Lift requirement to use a specific libprotoc version

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#2148]
**Is your feature request related to a problem? Please describe.**
Currently, we force usage of `libprotoc` version `3.12.4`.

**Describe the solution you'd like**
Lift the constraint to use that specific version. This can be done once the protobuf files are generated during the build stage.

**Comment by eorituz** [comment]
I'm sure it's just a typo but the aea cli told me that `libprotoc==3.11.4` is required.
It would also be awesome if you could add the specific required version when the aea cli checks for the existence of `libprotoc`.
I didn't have it installed and the cli "just" told me that `libprotoc` is missing and pointed me to the docs page but didn't mention a version. I installed latest just to figure out afterward that a specific version is required.
