### ISSUE TITLE
Manager and certs automation

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#2155]
**Is your feature request related to a problem? Please describe.**
The manager can further automate several things.

**Describe the solution you'd like**
- [x] packages with cert requests should be detected and then the save path automatically set to `working_dir/certs/`... (acfc026)
- [x] cert request save paths should be managed by the framework like build paths. That way the user does not have to worry about setting them correctly.
- [x] the manager working dir should have two dirs, one called `projects` with the projects inside, the other called `aliases` with all the alias info (`keys`, `certs`, other..)
- [X] mixed registry mode does not work on MAM (#2164)

**Comment by marcofavorito** [comment]
@DavidMinarsch please elaborate this:

> cert request save paths should be managed by the framework like build paths. That way the user does not have to worry about setting them correctly.
