### ISSUE TITLE
How to run echo skill demo with one terminal in laptop and the other in raspberry pi

### ISSUE THREAD

**Issue by maluachu** [fetchai/agents-aea#2162]
Hi,

I'm new to this topic and had tried the echo skill demo given in the documentation. It worked fine.
Now, I would like to try running the same demo with 

> aea run

on ubuntu 18.04 laptop and 

> aea interact

on raspberry pi 4.

How can I do this?

**Comment by DavidMinarsch** [comment]
Hi @maluachu , the echo skill demo must be run against the same folder. The messages are exchanged over the file system (`input_file` and `output_file`). I don't think your usage is supported. However, all the other demos can be run like this.
