### ISSUE TITLE
AeA issue-certificates is not working with connections out of vendor folder.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#2182]
**Describe the bug**
When I am using aea issue-certificates  it doesn’t like my custom connection.  I am getting this error :
`aea.exceptions.AEAException: Resource vendor/ddn/connections/kafka_connection does not exist.`

**To Reproduce**

Create a connection, and try to generate the certificates by running the command : `aea issue-certificates`

**Expected behaviour**

Should not have problem with custom connections. Currently I need to move my connection to vendor folder in order to successfully generate the certificates.

**Comment by DavidMinarsch** [comment]
@solarw correctly identified this to be an issue with @Totoual 's author not matching the non-vendor authors. So the package should be placed in vendor. Problem solved.
