### ISSUE TITLE
Investigate security issues on wallet private key handling.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#221]
**Is your feature request related to a problem? Please describe.**

Check security issues re. private keys generation/handling.

**Describe the solution you'd like**

None in particular.  Open for discussion.

**Describe alternatives you've considered**

None.

**Additional context**

Take into account the current best practices.

**Comment by DavidMinarsch** [comment]
Also clean up keyfile names; should be `{identifier}_private_key.txt`
