### ISSUE TITLE
Modify fetch_beacon skill to use ledger_api:get_state function

### ISSUE THREAD

**Issue by jrriehl** [fetchai/agents-aea#2232]
**Is your feature request related to a problem? Please describe.**
The `fetch_beacon` skill currently uses the `http_client` to get the random beacon value. Since we now have the ability to get this value via the `ledger_api`'s `get_state` method, it makes sense to use that instead. This would also avoid duplicating functionality of the `coin_price` and `simple_data_request` skills.

**Describe the solution you'd like**
The FetchBeaconBehaviour should send a message to the `ledger_api` connection with performative `GET_STATE`, which will return the latest block information, including the random beacon value. Then the `http_client` connection can be removed.

**Comment by DavidMinarsch** [comment]
Sounds good!
