### ISSUE TITLE
MAM: remove project and it's files when the last agent of that project deleted

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#2295]
**Is your feature request related to a problem? Please describe.**
Currently if you remove all agents and restart the MAM the project files stays there. It shuld be removed so user can add it again.

**Describe the solution you'd like**
- remove the project without agents
- remove project files so it can be fetched again

**Additional context**
![image](https://user-images.githubusercontent.com/6476789/108860829-416d8300-75f7-11eb-9d37-7a251b91e246.png)

**Comment by DavidMinarsch** [comment]
This functionality should be enabled via a flag on MAM initialisation and by default be disabled.
