### ISSUE TITLE
MAM: the agent re-created successfully from save but failed to start because component is outdated

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#2296]
**Describe the bug**
MAM: the agent re-created successfully from save but failed to start because component is outdated

**Expected behavior**
If agent and/or it's components are outdated (doesn't support current AEA version) it should fail on building it.

**Screenshots**
![image](https://user-images.githubusercontent.com/6476789/108861169-9b6e4880-75f7-11eb-9a08-fa2111fc5873.png)

**Comment by DavidMinarsch** [comment]
Building isn't the right term here. Reconstructing Alias from save file is what you mean.

**Comment by DavidMinarsch** [comment]
In add_project under `Project.load` do this check. If it's not compatible, move the configuration to "deprecated_file".
