### ISSUE TITLE
Include constraint type in OEF constraints.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#23]
**Is your feature request related to a problem? Please describe.**
The OEF models implemented in the `aea` package (that is, `Query`, `ConstraintExpr` etc.) still depend on the `oef` package for the `ConstraintType` classes. It should be possible to get rid of this dependency by including the constraint type feature in `aea`.

**Describe the solution you'd like**
Instead of replicating the [full class hierarchy](https://github.com/fetchai/oef-sdk/blob/master/oef/src/python/query.py#L226-L698), a more flexible approach would be to use some string codes to specify the type of constraint.

For example:
- Greater than: `">"`
- Greater or equal than: `">="`
- Equal to: `"="`
- ...

The codes could be further expanded upon request.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DavidMinarsch** [comment]
This is an issue in this file: aea/protocols/oef/models.py
