### ISSUE TITLE
AEA upgrade ERROR, to => aea v0.10.00 <v0.11.0

### ISSUE THREAD

**Issue by KY-BChain** [fetchai/agents-aea#2313]
aea upgrade
Starting project upgrade...
Checking if there is a newer remote version of agent package 'Kraken/BlockEnergy:0.4.0'...
Package not found, continuing with normal upgrade.
Error: Package Kraken/simple_seller:latest details can not be fetched from the registry!

**Comment by KY-BChain** [comment]
Report as per Agent World 4 (AW-4) agent-themed incentivised testnet
https://docs.fetch.ai/i_nets/quickstart-aw4/
If you are using an AEA which has been developed for a version of the AEA framework lower than 0.9.0 then please follow these steps to upgrade it:

    Run aea upgrade from within your AEA project. If you have any errors during this step then please log them as a GitHub issue and reach out on Discord. Additional instructions can be found here.

**Comment by DavidMinarsch** [comment]
Thanks! I can confirm this is a bug. Looking into it..
