### ISSUE TITLE
Inconsistent handling of multiple agents with same private key

### ISSUE THREAD

**Issue by eorituz** [fetchai/agents-aea#2320]
**Describe the bug**
The framework allows me to run two AEAs using the same private key without informing me about any issues. 
Obviously only one of the AEAs will work: I'd like to get some sort of feedback however that one AEA is not working anymore.

Once I start a third AEA using the same private key again I get a registration error:
```
[ERROR]: Agent registration error - page address or token not received. Response text: <?xml version="1.0" encoding="UTF-8"?><response><code>403</code><reason>Forbidden</reason><detail>already an agent, sign reclaim to recover</detail></response>
[INFO]: [simple_seller] received oef_search error message=Message(sender=fetchai/soef:any,to=fetch1yvk5jz8y4h7pftxeherf76utl6yk5mra034e2g,dialogue_reference=('618f6a767843417e2e9f0d9f24c9f3e65cdc7878dc096927468bf96a8bad0fae', '385f4ab01e678ef57e31a057d499f61a92ce9b75e8a3fc891581e5645d069bf7'),message_id=-1,oef_error_operation=10000,performative=oef_error,target=1) in dialogue=Dialogue Label:
618f6a767843417e2e9f0d9f24c9f3e65cdc7878dc096927468bf96a8bad0fae_385f4ab01e678ef57e31a057d499f61a92ce9b75e8a3fc891581e5645d069bf7_fetchai/soef:any_fetch1yvk5jz8y4h7pftxeherf76utl6yk5mra034e2g
Messages:
message_id=1, target=0, performative=register_service
message_id=-1, target=1, performative=oef_error
```

**To Reproduce**
1. Run two AEAs using the same private key
---> I wasn't able to reproduce this issue. I tried to restart both allegedly working AEAs and ran into the registration error with the second AEA. Maybe it was a "Blockchain sync" thing. The registration of the first AEA might have been not finalized before I started the second AEA. 

**Expected behavior**
I would expect the registration error message every time I start an AEA with an already in use private key

**Desktop (please complete the following information):**
```
root@fetch:~# uname -a
Linux fetch 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
I used the same machine and therefore the same IP for all AEAs I ran.

**Comment by DavidMinarsch** [comment]
Hi @eorituz thanks for reporting. There is no central entity controlling private key usage. You, as the owner of a pair, are responsible to managing it.

It is the responsibility of the services your AEA uses to report any issues with multiple keys being used simultaneously by different entities. E.g. the SOEF will report if two AEAs use the same key (and therefore address) to send requests.

In the case of the ACN, the only thing an ACN node can do in this scenario is to treat every message it receives on its merit. The first agent will registered on the ACN, then when the second agent registers an error will occur.

You say that on one occasion the second agent was able to register whilst the first one was still registered without a resulting error message. We'll take a look if we can reproduce it, although initial investigation suggests the behaviour is as expected and the error occurs for the second agent.

We'll also check if the error messages are sufficiently informative.
