### ISSUE TITLE
Echo agent output going to stderr

### ISSUE THREAD

**Issue by dishmop** [fetchai/agents-aea#236]
**Describe the bug**
When running the cli_gui, the TTY output from the echo agent is all coming out as stderr rather  than stdout.

**To Reproduce**
from command line type:
aea gui
Open browser at correct page
Stat oef node
Create an agent with echo skill
run the agent - only text form stderr (red) appears

**Expected behavior**
Should have text in both boxes appearing

**Desktop (please complete the following information):**
OSX

**Comment by dishmop** [comment]
> When running the cli_gui, the TTY output from the echo agent is all coming out as stderr rather than stdout.

**Comment by DavidMinarsch** [comment]
Lot's of good info here: https://www.techatbloomberg.com/blog/guide-logging-python/

**Comment by DavidMinarsch** [comment]
@marcofavorito I think our home-made approach to logging (e.g. `logger = logging.getLogger("aea.echo_skill")`) might cause this.
