### ISSUE TITLE
CLI version vs package requirements blocking

### ISSUE THREAD

**Issue by eorituz** [fetchai/agents-aea#2360]
**Describe the bug**
When adding a protocol (also works with agents etc.) that requires a different aea CLI version the installation succeeds but afterwards any further CLI command get's blocked due to version inconsistency. 
```
Error: The CLI version is 0.10.0, but package fetchai/http:0.13.0 requires version <0.12.0,>=0.11.0
```

**To Reproduce**
1. Install aea 0.10.0
2. Add a protocol/agent/package which requires another CLI version. e.g. `aea add protocol fetchai/http:0.13.0` (requires 0.11+)
3. Any other aea CLI command will result in an error due to the version inconsistency. 

**Expected behavior**
I would expect to at least be able to remove the "wrong" protocol:
```
(sensor_demo_aea) oliver@bbpc:~/Arbeit/aea/sensor_demo/buyer$ aea remove protocol fetchai/http:0.13.0
Error: The CLI version is 0.10.0, but package fetchai/http:0.13.0 requires version <0.12.0,>=0.11.0
```
This should not throw an error but work. Given the current state, I have no option to get rid of the mistakenly added protocol.
Sucks pretty hard because one can't simply delete some files to get rid of the protocol manaually (at least I wasn't able to come up with it in a reasonable amount of time) --> I had to hard reset to the last commit.

**Desktop (please complete the following information):**
 ```
(sensor_demo_aea) oliver@bbpc:~/Arbeit/aea/sensor_demo/buyer$ uname -a
Linux bbpc 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
 - AEA Version: 0.10.0

**Additional context**

**Comment by DavidMinarsch** [comment]
Thanks for the report. We'll fix it for v1.0.0rc next week.
