### ISSUE TITLE
Make `required_ledgers` a required field.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#2387]
**Is your feature request related to a problem? Please describe.**

In #2386, `required_ledgers` has been introduced as an optional field in agent configuration files.

However, that field should be made mandatory; the only reason why it was an optional field is to make it an easier feature to add without breaking several integration tests (e.g. a common issue was due to the fact that when computing the difference between the locally built agent and the fetched agent from the registry, the configuration field local built agent had the field whereas the one of the fetched agent didn't).

Analogously, in #2389 , `message_format` should be made a required field.

**Describe the solution you'd like**
- Make the field as required in AEA configuration JSON schema
- Remove `required_ledgers` as 'allowed field to be different' in `difference_to_fetched_agent`.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
Also make `"message_format"` a required field in `cert_requests`.

**Comment by DavidMinarsch** [comment]
Also applies to `registry_path` needing to be removed.

**Comment by DavidMinarsch** [comment]
![Screenshot 2021-03-23 at 14 48 52](https://user-images.githubusercontent.com/19314578/112348983-3e31e980-8cc0-11eb-962b-ed78641a7739.png)
