### ISSUE TITLE
Update docker deploy readme/examples/docs

### ISSUE THREAD

**Issue by eorituz** [fetchai/agents-aea#2394]
**Is your feature request related to a problem? Please describe.**
I'd like to build & run docker container using my (only local) agents.

**Describe the solution you'd like**
- The docker deploy readme seems out of date https://github.com/fetchai/agents-aea/tree/main/deploy-image: The github repo `https://github.com/fetchai/echo_agent.git` is either not accessible for the public or doesn't exist anymore. --> However I'd like to have an example repo to know what files need to be included and how the structure of an "agent repo" should look like

- It would also be amazing to have a bit more documentation about the params one needs to adapt to run custom agents in docker. E.g.  Docker env / params in the scripts that can/should be changed.

-  I'd love to see an option in the docker run scripts to use a local directory as agent instead of a github repo [optional, it's just nice for testing ofc it won't be necessary for "production"]

- The docker tag is inconsistent. The [docker run command](https://github.com/fetchai/agents-aea/tree/main/deploy-image#run) tries to run `aea-deploy:latest` which doesn't exist locally. It should either be `fetchai/aea-deploy:latest` or you adapt the docker tag in the [build command](https://github.com/fetchai/agents-aea/tree/main/deploy-image#build).  I would use the tag `fetchai/aea-deploy:latest`. This way it doesn't matter where the user build it first or not.

**Describe alternatives you've considered**
I think it might be faster for me atm to just write Dockerfiles myself. (Understanding the shell scripts setup takes more time than writing a Dockerfile)

**Comment by DavidMinarsch** [comment]
Hi @eorituz , I'm sure we can do something about that :). Thanks for letting us know!
