### ISSUE TITLE
local variable 'oef_message' referenced before assignment

### ISSUE THREAD

**Issue by neerajkumarbansal** [fetchai/agents-aea#2395]
Description: 
On line 333 in connection.py file of Soef Connection, oef_message is used in the catch block but defined inside the try block.

Traceback:
`Traceback (most recent call last):
  File "vendor/fetchai/connections/soef/connection.py", line 333, in _find_around_me_processor
    oef_message,
UnboundLocalError: local variable 'oef_message' referenced before assignment
`

Enviornment:
 - AEA Version 0.11.2
 - Package Version (fetchai/soef:0.19.0)

**Comment by DavidMinarsch** [comment]
@neerajkumarbansal thanks for reporting. We'll try to fix this asap.
