### ISSUE TITLE
Unable to receive message on the Fipa Handler after 10 minutes of inactivity

### ISSUE THREAD

**Issue by neerajkumarbansal** [fetchai/agents-aea#2396]
Description:
I have two types of agents i.e Product Agents and Supply Agents. where product agents go to the network to buy certain items and Supply agents provide those agents. So, when I generate a CFP message from the Product Agent to the required Supply Agents on the network for that particular item, the Supply Agents successfully receive those messages does there required work perfectly fine. But after like 10 minutes of Inactivity, the Supply agent stops receiving any messages from FIPA Handler.

I am using MAM in order to create and manage my agents.

Expected behaviour:
Supply Agents should receive Fipa Messages any time they has been ask for it.

Enviornment:
 - Ubuntu 20.04 ( Linux)
 - AEA Version 0.11.2
 - Fipa Protocol : fetchai/fipa:0.14.0
 - P2p Client Connection : fetchai/p2p_libp2p_client:0.14.0

Additional Information:
I suspect there is an issue with issuing certificates with MAM. this is getting logged after which it stops receiving any messages.

`issue_certificates.py:158  | DEBUG    No certificates to process.
issue_certificates.py:158  | DEBUG    No certificates to process.
issue_certificates.py:161  | DEBUG    Processing connection 'fetchai/p2p_libp2p_client:0.14.0'...
`

This is the component override part for p2p_libp2p_client.

`{
                'author': 'fetchai',
                'name': 'p2p_libp2p_client',
                'version': '0.14.0',
                'type': 'connection',
                "cert_requests": [
                    {
                        "identifier": "acn",
                        "ledger_id": "fetchai",
                        "not_after": '2022-01-01',
                        "not_before": '2021-01-01',
                        "public_key": "0217a59bd805c310aca4febe0e99ce22ee3712ae085dc1e5630430b1e15a584bb7",
                        "save_path": f"{self._manager.data_dir}/certificate_1_{agent_id}.txt"
                    },
                    {
                        "identifier": "acn",
                        "ledger_id": "fetchai",
                        "not_after": '2022-01-01',
                        "not_before": '2021-01-01',
                        "public_key": "03fa7cfae1037cba5218f0f5743802eced8de3247c55ecebaae46c7d3679e3f91d",
                        "save_path": f"{self._manager.data_dir}/certificate_2_{agent_id}.txt"
                    },
                ]
            },`

One more thing, It again works fine when i restart the agent. but the same thing happens after 10 mins.

**Comment by DavidMinarsch** [comment]
Hi @neerajkumarbansal, please provide details on how to reproduce the problem (e.g. some code we can run ourselves to see the problem). Since you initially receive messages this is unlikely related to certificates (the message you shared does not indicate any problem either).

**Comment by neerajkumarbansal** [comment]
This is the repo and the branch I am working on:-
[https://github.com/fetchai/supply-chain/tree/enhancement/order_mechanism](URL)

You can do docker-compose build and docker-compose up -d. In order to run the required services. You will be able to see the frontend running on localhost:8080. You can create the Product and Supply Agent from there. make sure they are nearby and have the same article name. and once the agents are up and running you can go to the Product Agent Detail screen by clicking on the product agents and click the Ask for Price and Time Button. and then you can try clicking that button after 10 min.
