### ISSUE TITLE
Better check for some code variable using RE to amtch jsonschema

### ISSUE THREAD

**Issue by solarw** [fetchai/agents-aea#2401]
dependency class: git/index are str url, but not validated for url
resource_name: agent name for example, mostly str in code, and looks not checked  with RE
ledger_id: has RE in jsonschema , not sure checked anywhere in code.

solution:
force check on argument passing, settin attributes

**Comment by DavidMinarsch** [comment]
The agent name is validated when the identity object is constructed (`SimpleId`). We could add additional validation in manager but not strictly needed as it is provided by the called upon objects.

`ledger_id` needs checking throughout...
