### ISSUE TITLE
Check several minor issues in p2p_libp2p* connections.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#2435]
**Describe the bug**
Check implementation of `p2p_libp2p` and `p2p_libp2p_client` connection regarding:
- reconnection mechanism (making sure that no envelope is lost)
- connection state machine (i.e. that all the states the stateful connection can be in are implemented correctly)
- error handling (e.g. if `_writer` is `None`, a ValueError is catched, but if `_reader` is `None` it is not)

**To Reproduce**

TBD. Related to #2434

**Expected behavior**
TBD

**Screenshots**

Not applicable.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - AEA Version 1.0.0 (develop)

**Additional context**
n/a

**Comment by DavidMinarsch** [comment]
After ensuring no envelope is lost, adjust this test:
![Uploading Screenshot 2021-04-13 at 09.23.41.png…]()
