### ISSUE TITLE
CLI_GUI: easy to make submit multiple versions of same request

### ISSUE THREAD

**Issue by dishmop** [fetchai/agents-aea#245]
**Describe the bug**
It is not clear when a button (e.g. remove) has been pressed once and is just waiting for server to respond so user can easily submit twice. Would be better to update ui (i.e.) clear selection as soon as button is pressed (rater then waiting for response).

**Comment by DavidMinarsch** [comment]
You could also disable the button on the client side until the page is refreshed.

**Comment by dishmop** [comment]
I've already submitted a fixfor this along the lines you suggest.
