### ISSUE TITLE
Windows install error

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#2469]
**Describe the bug**
A user reported a problem with aea install on Windows.

We have a check for this in CI but looks like the check is not sufficient.

**To Reproduce**
1. Use Windows
2. Using Powershell, type `pipenv shell`
3. Install `pip install aea[all]`
4. Run `aea --version`
5. See:
```
import win32process  # type: ignore  # pylint: disable=import-error
ModuleNotFoundError: No module named 'win32process'
```

**Expected behavior**
No problem.

**Working Theory**
Something goes wrong with install. In `setup.py` we use a different check for platform/os than when we import:

https://github.com/fetchai/agents-aea/blob/main/setup.py#L64
vs
https://github.com/fetchai/agents-aea/blob/main/aea/helpers/profiling.py#L42

**Comment by DavidMinarsch** [comment]
Relevant: https://stackoverflow.com/questions/4553129/when-to-use-os-name-sys-platform-or-platform-system

**Comment by Vesth** [comment]
Originally used the automated script install.ps1, but ran into (probably) the same error. AEA was installed but not be run. Afterwards followed the manual approach and ran into the problem above. As mentioned by David, `pip install pywin32` solved the issue

**Comment by DavidMinarsch** [comment]
Turns out it was a problem with the way the wheel's were created. Fixed with next release.
