### ISSUE TITLE
Missing tests for password usage

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#2471]
**Is your feature request related to a problem? Please describe.**
We should add tests for password usage in CLI and manager

**Describe the solution you'd like**
Obvs.

**Comment by marcofavorito** [comment]
Done (#2516):

- `get-address`
- `generate-key`
- `add-key`

**Comment by marcofavorito** [comment]
Missing/to be checked:

- [ ] `get-wealth`
- [ ] `get-multiaddress`
- [ ] `init`
- [ ] `issue-certificates`
- [ ] `launch`
- [ ] `reset-password`
- [ ] `run`
- [ ] `transfer`
