### ISSUE TITLE
MAM: error installing an agent dependency if already present

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#2521]
**Describe the bug**
MAM: error installing an agent dependency if already present.
If the dependency (`aiohttp`) already present installation return code `!=0` and that is recognized as a failure.

**To Reproduce**
1. Install `aiohttp<3.8>=3.7.4`
2. Try to fetch an agent `fetchai/simple_seller_aw5:0.2.0`
3. See error

**Expected behavior**
Agent is succesfully added.

**Screenshots**
From AEA Manager:
![image](https://user-images.githubusercontent.com/6476789/119001376-96215f80-b994-11eb-97d7-bda76fb6a044.png)

**Desktop (please complete the following information):**
 - OS: any
 - AEA Version 1.0.1

**Comment by panasevychol** [comment]
Possible solutions:
- Use flag to reinstall the dependency (for the case if version doesn't match)
- Recognize the case if dependency is present

**Comment by DavidMinarsch** [comment]
A dependency mismatch across agent projects cannot be engineered away. What we can do is provide more helpful error message. We could say: dependency x which you are trying to install with permitted versions y cannot be installed because it is already present with version z from project zz.

**Comment by marcofavorito** [comment]
@panasevychol I can't reproduce the issue. Can you help me?

I am trying to reproduce it on a Ubuntu Docker container.

```
docker run -it ubuntu:20.04 /bin/bash
```

Then, copy-paste the following commands:
```
apt-get update
apt-get install python3-dev python3-pip
pip install "aiohttp<3.8>=3.7.4"
pip install "aea[all]"
aea fetch fetchai/simple_seller_aw5:0.2.0
cd simple_seller_aw5
aea install
```

**Comment by marcofavorito** [comment]
I have also tried to add the project in a MAM. 
First, install `aiohttp`:

```
pip install "aiohttp<3.8>=3.7.4"
```

Then, run the following code in a Python console (with the same interpreter):
```python


import os
from pathlib import Path
from aea.manager import MultiAgentManager
from aea.configurations.base import PublicId

WORKING_DIR = "mam"

manager = MultiAgentManager(WORKING_DIR)
manager.start_manager()
public_id = PublicId.from_str("fetchai/simple_seller_aw5:0.2.0")
manager.add_project(public_id)
```

I couldn't get the error.
