### ISSUE TITLE
Simplify publishing aeas locally

### ISSUE THREAD

**Issue by eorituz** [fetchai/agents-aea#2531]
**Is your feature request related to a problem? Please describe.**
I wrote my own trading aea. This involves some of my code as well as a lot of connections, protocolls etc (from the docs trade example). 
I wanted to push & publish it locally to dockerize it. 
If I understood it correctly I'd have to manually `aea push` every single skill, connection, protocoll, contract that I want to use (even though the majority are in the registry) in order to be able to `aea publish` my aea.

**Describe the solution you'd like**
1) It would be amazing to have a bit more detailed docs about handling aeas locally 
2) It would also be amazing to have the abillity to just `aea push` everything at once and be able to run `aea publish` after that. (This would require the aea to check the local source folder as well as the registry to collect all the needed skills/connections etc.)

**Describe alternatives you've considered**
Add a new option to the aea cli which pushes and publishes a certain aea with all it's components. - Basically, remove the need to push every single component bevore beeing able to publish the aea.

**Additional context**
Related error message:
```
(trade_aea) oliver@bbpc:~/Arbeit/aea/dockerize_trade_aea/my_generic_seller$ aea publish --local
Error: Dependency is missing. Item "soef" not found in source folder.
Please push it first and then retry.
```
I pushed my skill and expected the `aea publish` command to collect the missing dependencies from the registry

**Comment by DavidMinarsch** [comment]
I think we could extend the `aea publish` command to automatically push unpushed dependencies to the registry (local and remote). This would simply involve calling the `push` functionality for the unpushed packages from within the execution context of the publish. We have the internal business logic to determine the push order (inverse dependency tree) already.
