### ISSUE TITLE
Decision Maker Decision Scaffold out of Date

### ISSUE THREAD

**Issue by 8ball030** [fetchai/agents-aea#2583]
**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.fetch.ai/aea/decision-maker/'
2. Do 'run the command' 
 ```aea scaffold decision-maker-handler```
3. See error '...'
```
(agents) tom@gefion~/D/c/d/m/m/A/a/t/mobix_user_agent> aea scaffold decision-maker-handler
Error: Agent configuration file 'aea-config.yaml' is invalid: `The following errors occurred during validation:
 - decision_maker_handler: 'config' is a required property`. Please check the documentation.
(agents) tom@gefion~/D/c/d/m/m/A/a/t/mobix_user_agent> 

```
**Expected behavior**
I would  expect a custom decision maker to generated as  package as referenced in the documentation linked.

**Screenshots**

**Desktop (please complete the following information):**
 - AEA Version [e.g. 1.0.0]

**Additional context**

**Comment by DavidMinarsch** [comment]
Good one! We need to also improve the docs and scaffolding: https://docs.fetch.ai/aea/decision-maker/
