### ISSUE TITLE
Not able to stop a skill from a skill.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#265]
**Is your feature request related to a problem? Please describe.**

I can't stop my agent when some condition is satisfied.

**Describe the solution you'd like**

Being able to stop the agent from the code of a skill.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by DavidMinarsch** [comment]
Currently, a skills handler and behaviour get called by `react()` and `act()` indefinitely (as long as the agent runs). It should be possible to `deactivate` the skill from the main loop programmatically. For handlers, if a handler is inactive, it should no longer be returned in this call `handlers = self.filter.get_active_handlers(protocol.id)` in `react()`. For behaviours, similarly, if a behaviour is inactive, it should no longer be returned in this call `behaviour in self.filter.get_active_behaviours()` in `act()`. The `inactive` skill components should be tracked in the `Filter` (see TODOs in the initialization there). This way, a component can be `activated` again later. We *do not* want to deregister the components when they are inactive. Once this has been implemented, the new functionality should be applied to the existing skills (especially the tac participate skill).
