### ISSUE TITLE
Custom types are not accounted for when inside other types (e.g. `pt:union`)

### ISSUE THREAD

**Issue by 5A11** [fetchai/agents-aea#2763]
### Prerequisites

- [X] I am running the [latest version of the AEA Framework](https://docs.fetch.ai/aea/version/).
- [X] I checked the [documentation](https://docs.fetch.ai/aea/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/agents-aea/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/agents-aea/blob/main/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

The generator must take into custom types as they appear inside other types (`pt:union` and `pt:optional`).

### Current Behavior

When using `pt:union[...]` if there is a custom type (`ct:...`) inside, and the custom type does not appear in other speech-acts as a standalone type, the generator does not recognise it and gives an error on the (unrecognised) protobuf snippet.

### Context

All

**Comment by danielksan81** [comment]
Does this issue relate to #2599 ?

**Comment by 5A11** [comment]
> Does this issue relate to #2599 ?

No

**Comment by 5A11** [comment]
The fix for this bug is now in develop and will be included in the next release.
