### ISSUE TITLE
Bug report: Dependecies conflict using aea-ledger-ethereum

### ISSUE THREAD

**Issue by mariacarmina** [fetchai/agents-aea#2770]
### Prerequisites

- [X] I am running the [latest version of the AEA Framework](https://docs.fetch.ai/aea/version/).
- [X] I checked the [documentation](https://docs.fetch.ai/aea/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/agents-aea/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/agents-aea/blob/main/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

To work well when installing ocean-lib==1.2.0 and aea-ledger-ethereum==1.10

### Current Behavior

`ocean-lib` does not use a lower version than 5.20 for web3 and `aea-ledger-ethereum` requires web3==5.12 and that generates dependency conflict.

### To Reproduce

Try installing in a python environment the following dependencies:
```console
pipenv --python 3.8
pipenv shell
pipenv install --skip-lock ocean-lib==1.2.0
pipenv install --skip-lock aea-ledger-ethereum ==1.1.0
```

### Context

Operating system: Ubuntu 20.04, Python 3.8

### Failure Logs

```
[pipenv.exceptions.InstallError]: The conflict is caused by:
[pipenv.exceptions.InstallError]:     aea-ledger-ethereum 1.1.0 depends on web3==5.12.0
[pipenv.exceptions.InstallError]:     ocean-lib 1.2.0 depends on web3==5.28.0
[pipenv.exceptions.InstallError]: ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by 5A11** [comment]
This was in PR #2774 which was merged. Just have wait for base PRs to be merged and make it into the next release.
