### ISSUE TITLE
Introduce `ConnectionMultiplexer` abstraction

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#334]
**Is your feature request related to a problem? Please describe.**

It should be easy to handle multiple connections at once. Currently, the mailbox does not make this task easy.

**Describe the solution you'd like**

A further abstraction, a `Multiplexer`, that let the agent use multiple connections at once, potentially of different nature.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by DavidMinarsch** [comment]
- We should only use asyncio features which are backwards compatible to Python 3.5 inclusive
- We should keep the connections interface straightforward so that developers without much understanding of asyncio can develop their own `connections`
