### ISSUE TITLE
Name of agents shared with other agents

### ISSUE THREAD

**Issue by dishmop** [fetchai/agents-aea#357]
**Is your feature request related to a problem? Please describe.**
At the moment any display of any messages can reference self with make of agents, but can't say name of other agent we are interacting with. 

**Describe the solution you'd like**
Perhaps part of protocol specific implementations.

**Comment by DavidMinarsch** [comment]
This issue is best addressed by the developer using a protocol which allows to send a name as part of a message. It does not make sense to introduce a name field on the Envelope level as it is a special rather than generic use case.
