### ISSUE TITLE
Add `connections` resources.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#41]
**Is your feature request related to a problem? Please describe.**

Currently, the `AEA` agent can be run in two ways:
- by interacting directly with the Python library. That is, instantiate an `AEA` instance, set the `mailbox` with the specific `Connection`, and then `start()` the agent.
- by using the `aea` command-line tool (in particular, the `aea run` subcommand), which uses the `OEFConnection`.

**Describe the solution you'd like**

Let the `AEA` agent support multiple connection layers, and be able to run it with one of the connections defined in his resource folder.

More in detail:
- create a new `connections/` folder inside the agent's resource directory.
- support `aea add connection ...` to add a new connection module (and `aea remove` to remove it)
- Let the user be able to specify the connection to use when running `aea run`, using a flexible way to forward the parameters.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by DavidMinarsch** [comment]
This in particular should work with `oef`, `local` and `gym` channels to begin with.
