### ISSUE TITLE
Multiple connections in cli `run` command

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#423]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by marcofavorito** [comment]
@DavidMinarsch do we prefer:
```
aea run --connection conn_1_id --connection conn_2_id ...
# or, equivalently
aea run -c conn_1_id -c conn_2_id ...
```

OR
```
aea run --connections conn_1_id conn_2_id ...
```

?

**Comment by DavidMinarsch** [comment]
I prefer the second, you?
