### ISSUE TITLE
Agent wont disconnect properly

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#426]
**Describe the bug**
Disconnection issues with the agents:

<img width="608" alt="Screenshot 2019-11-22 at 11 04 50" src="https://user-images.githubusercontent.com/19314578/69423096-90a67300-0d25-11ea-862f-a1f7bb4a3060.png">

**Comment by marcofavorito** [comment]
The issue is that the `teardown` method of `weather_station` behaviour assumes the connection is still up and tries to send a put a message on the oubox. However, that is not possible, since in the method `Agent.stop` the connection has already been torn down when `Behaviour.teardown` is called.
