### ISSUE TITLE
Refactoring ideas Marco

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#456]
management of configurations & interface with file system (backwards compatible > later); separation of command line and registry;

Easier to have a start with the SDK but now easier and faster for him to build in the framework > startup cost is more expensive but then get started

**Comment by DavidMinarsch** [comment]
Entity component system

**Comment by DavidMinarsch** [comment]
Other priorities w framework:
- Make it easy to read
- Reduce duplication where feasible
- Require less type casting!

**Comment by marcofavorito** [comment]
Refactor the `LedgerApis` class.
- Make it abstract, and let instantiation of it for each cryptocurrency supported (e.g. `EthereumLedgerApis`, `FetchaiLedgerApis`)
