### ISSUE TITLE
MLTradeMessage.__eq__ cannot compare the 'data' field.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#496]
**Describe the bug**

`MLTradeMessage.__eq__`  does not work when the `"data"` field is set.

**To Reproduce**
Omitted.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
`aea` version: `v0.1.14`

**Smartphone (please complete the following information):**
N/A 

**Additional context**

**Comment by Totoual** [comment]
You can reproduce with the following code : 
`    data = np.zeros((5, 2)), np.zeros((5, 2))
    msg = MLTradeMessage(performative=MLTradeMessage.Performative.DATA, terms=terms, data=data)
    msg_bytes = MLTradeSerializer().encode(msg)
    reverted_msg = MLTradeSerializer().decode(msg_bytes)
    assert reverted_msg == msg
`

**Comment by marcofavorito** [comment]
To reproduce:
```python
import numpy as np
from aea.helpers.search.models import Description
data = np.zeros((5, 2)), np.zeros((5, 2))
terms = Description({"a_term": 1})
msg = MLTradeMessage(performative=MLTradeMessage.Performative.DATA, terms=terms, data=data)
msg_bytes = MLTradeSerializer().encode(msg)
reverted_msg = MLTradeSerializer().decode(msg_bytes)
assert reverted_msg == msg
```
