### ISSUE TITLE
Documentation of the existing AEA framework and provided examples

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#50]
**Is your feature request related to a problem? Please describe.**
Currently, no documentation of the framework exists.

**Describe the solution you'd like**
The existing AEA framework should be documented. Additionally, we should provide documentation of the available `protocols`, `skills` and `examples`.

**Describe alternatives you've considered**
None

**Additional context**
This will contribute to making the AEA framework ready for launch.

**Comment by marcofavorito** [comment]
What tools should be used? 
- Sphinx as in [agents-tac](https://github.com/fetchai/agents-tac)
- [Mkdocs](https://www.mkdocs.org/) as the [Fetch.AI Documentation](https://docs.fetch.ai/)
- something else?
