### ISSUE TITLE
Aea-config.yaml keeps false connections.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#517]
**Describe the bug**

`aea scaffold connection m_con` updates the aea-config.yaml file and adds the m_con even if it fails to scaffold the new connection.  That leads to a list of un-used connection names inside the aaa-config.yaml that we have to remove manually.

**To Reproduce**
1. Modify the 'connection-config_shema.json' in a way that will lead to "Error when validating the skill configuration file."
2. Check the aaa-config.yaml file.

**Expected behavior**
It either validate before writing the aaa-config.yaml file or remove after failing.

**Desktop (please complete the following information):**
 - OS

**Comment by DavidMinarsch** [comment]
@panasevychol considers as done, closing
