### ISSUE TITLE
Change import system to support multiple agents in the same process.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#607]
**Is your feature request related to a problem? Please describe.**
Currently, the import schema `packages.author.package_type_pluarlised.package_name` does not allow multiple agents to run in the same process, since the import paths are in conflict.

E.g. suppose both `agent_1` and `agent_2` have a `fetchai/echo:0.1.0` skill. If for some reason the code one of the two skills is modified, one of the two agent cannot import its skill code, because only the last imported module will be stored in `sys.modules`.

**Describe the solution you'd like**
A way to disambiguate the packages when two agents are run in the same process.

**Describe alternatives you've considered**

**Additional context**

If we enforce the framework to have "one agent per one process" then this issue is automatically solved.

Somehow related: once the agent has been stopped, the framework should unload the content of `sys.modules` associated to the agent components modules.

**Comment by DavidMinarsch** [comment]
Seems straightforwardly solved by prepending `agent_name` to the import schema.

Re unloading content, see: https://stackoverflow.com/questions/437589/how-do-i-unload-reload-a-module/487718#487718

**Comment by DavidMinarsch** [comment]
Done, although we assume all packages in one process have matching versions!
