### ISSUE TITLE
Use `author/package_name` in AEA business logic

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#615]
**Is your feature request related to a problem? Please describe.**
Currently, only `package_name` is used in the AEA business logic

**Describe the solution you'd like**
Use `author/package_name`  rather than simply `package_name` to identify connections and protocols in the business logic of the AEA.

**Comment by marcofavorito** [comment]
the public id will be used when possible, o/w the `author/package_name`.
