### ISSUE TITLE
Let the initialization of a behaviour action from constructor

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#642]
**Is your feature request related to a problem? Please describe.**
?

**Describe the solution you'd like**
?

**Comment by DavidMinarsch** [comment]
@marcofavorito you created this TODO..care to elaborate?

**Comment by marcofavorito** [comment]
@DavidMinarsch let suppose you want to create a `OneShotBehaviour` that calls the following function:

```python
def hello():
    print("Hello, World!")
```

With the current state of the Behaviour APIs, you have to define a class `HelloWorldBehaviour` as a subclass of `OneShotBehaviour` and call the function in the `act()` method. Namely:

```python
class HelloWorldBehaviour(OneShotBehaviour):
    
    def act(self):
        hello()

```

What I'm proposing is to have something like:

```python
hello_behaviour = OneShotBehaviour(act=hello)
```

However, that would be beneficial only for programmatic instantiation of new behaviours. Making it doable from the `skill.yaml` configuration file requires more work.

**Comment by marcofavorito** [comment]
`setup` and `teardown` to be added as well.
