### ISSUE TITLE
Introduce versioning to Skills and Protocols and Connections

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#66]
**Is your feature request related to a problem? Please describe.**
Skills and protocols and channels should be versioned from the outset for obvious reasons.

**Describe the solution you'd like**
Obvious.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by marcofavorito** [comment]
After PR #153 is merged, the issues can be considered closed.
