### ISSUE TITLE
Ran python setup.py protoc --> error: invalid command 'protoc'

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/agents-aea#707]
**Describe the bug**
The setup.py in the root agents-aea dir doesn't recognize 'protoc' command.

**To Reproduce**
Run the following steps in order to reproduce the behavior:
1. `git clone https://github.com/fetchai/agents-aea.git --recursive && cd agents-aea`
2. `pipenv --python 3.7 && pipenv shell`
3. `pip install .[all] && pip install .[cli]`
4. `pipenv install --dev`
5. `pip install -e .`
6. `python setup.py protoc`

**Screenshot**
![Screenshot from 2020-02-04 17-12-43](https://user-images.githubusercontent.com/13785749/73792085-9ed72d80-4771-11ea-9365-47bbdb8f0a56.png)

**Desktop:**
 - OS: [e.g. Ubuntu 18.04.4 LTS]

**Protoc --version**
libprotoc 3.11.2

**Comment by marcofavorito** [comment]
Hi @Kevin-Chen0,

thank you for your feedback. The instruction for the instruction (6) `python setup.py protoc` is in fact outdated. We will fix the README soon.

An equivalent command can be:
```
find -name "*.proto" | xargs -I{} protoc --python_out=./ {}
```

However, worth reminding that that command is supposed to be used only when some `*.proto` file is changed.

**Comment by DavidMinarsch** [comment]
Hi @Kevin-Chen0, in addition to what @marcofavorito said above, I notice you install the library multiple times. It is sufficient to do the following after 2.: first `pipenv install --dev`, then `pip install -e.`. At this point you are ready to develop.
