### ISSUE TITLE
Error running tox -e py37 (deprecated?)

### ISSUE THREAD

**Issue by Kevin-Chen0** [fetchai/agents-aea#711]
Run `tox -e py37`

![image](https://user-images.githubusercontent.com/13785749/73854039-d7254d00-47ff-11ea-8190-f78906217f72.png)

![image](https://user-images.githubusercontent.com/13785749/73854142-020fa100-4800-11ea-91a0-cc2a54b9a45c.png)

**Comment by DavidMinarsch** [comment]
@Kevin-Chen0 the deprecation warning is not a bug as it is for tox 4.0 and we are using a lower version!

The error you experience suggests tox might not be installed?

**Comment by Kevin-Chen0** [comment]
No, I am using tox 3.7.0. Maybe it has something to do with the `testenv` warning?

![image](https://user-images.githubusercontent.com/13785749/73878937-81659a80-4829-11ea-8030-c8485907dd15.png)
