### ISSUE TITLE
Create a strategy file by default when you 

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#716]
**Describe the solution you'd like**

Currently, we are using Models to describe the agent's strategy, dialogues, etc. If we check all of the uses cases and demos we are using, every single one has an implementation of a strategy and a dialogue model. 

Can we consider creating the strategy model by default when we are scaffolding a skill? If we move to a direction that the Data_model and schema for the OEF are configurable from the `.yaml` file through the strategy that will make the strategy mandatory for every agent. That's the main reason I would suggest to create the simplest implementation of a strategy by default. Moreover, it makes more sense to have a file named `strategy.py` rather than `my_mode.py`l. It can still inherit from the model class but it is clearer for the developer what file is this and each purpose. 

If the developer wants to create another model, he is going to manually create the file. And he will probably refer to the documentation at this point.

**Comment by DavidMinarsch** [comment]
We want to keep the clarity in the three types of classes in a skill: `Model`, `Handler` and `Behaviour`. A "strategy" is not an AEA framework concept atm.
