### ISSUE TITLE
Increase test coverage to 100%, then enforce coverage via CI

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#73]
**Is your feature request related to a problem? Please describe.**
Currently, we have relatively low test coverage.

**Describe the solution you'd like**
To increase the stability of the library we should increase coverage to 100%.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Physsix27** [comment]
Hey, @DavidMinarsch I would love to contribute to this issue, can you please walk me through the python files that still need to be `unit test` and I work on it if no one is tackling it right now.

**Comment by DavidMinarsch** [comment]
Hey, @Physsix27 thanks for getting in touch and offering to help, very much appreciated! I just ran the test suite and got the following coverage report:
![Screenshot 2019-10-07 at 17 06 46](https://user-images.githubusercontent.com/19314578/66328825-4e67d480-e925-11e9-9dc4-0f9b82bdf4f2.png)

**Comment by DavidMinarsch** [comment]
Based on the above I suggest you focus on `aea/skills` and gets unit tests coverage up to 100%. Does that work for you? Please give us a quick heads up if so and when you expect to open a PR. We are moving very fast at the moment and want to avoid duplication of work :). @marcofavorito and @Totoual  will also be able to make suggestions if you have questions.

**Comment by Physsix27** [comment]
I will be working on this issue and focusing in `aea/skills`.
You can assign to me this issue

**Comment by Physsix27** [comment]
Hey @DavidMinarsch,  you don't have a `requirements.txt` with all the requirements need it to be installed to be able to use the project? I install dependencies from the `setup.py` with `make install` but I believe there are things missing.  Is it okay if I add that file with the extras needs in it and add those installations to the `make install` target?

**Comment by Physsix27** [comment]
let me know what I am missing before I start working on the tests, would like to have everything that needs it first. This is how is looking now.
![image](https://user-images.githubusercontent.com/36493537/66711342-f8959100-ed57-11e9-819c-9c28829c86aa.png)
