### ISSUE TITLE
Build a pet shop app using the AEA

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#740]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
Use generic HTTP connection package and build a skill which implements a simple pet shop app.

**Comment by DavidMinarsch** [comment]
what: an AEA skill that given an OpenAPI specification let the developer to easily implement methods to handle the REST requests. The popular PetStore example can be a starting point.
readiness: production
why: service-as-an-agent (SaaA) is a use case that fits well in the Fetch.AI ecosystem. Using standards such as OpenAPI will help developers to deliver good products.

**Comment by Kevin-Chen0** [comment]
Basically have the locally-spun Agents reenact this Pet Shop demo where they can deploy and interact with a Fetch or Ethereum Pet Shop smart contract on a testnet via HTTP connection? https://github.com/fetchai/etch-demos
