### ISSUE TITLE
Explore running AEA in Pyodide

### ISSUE THREAD

**Issue by DavidMinarsch** [fetchai/agents-aea#741]
**Is your feature request related to a problem? Please describe.**
The Python based AEAs can not run on web browsers.

**Describe the solution you'd like**
https://hacks.mozilla.org/2019/04/pyodide-bringing-the-scientific-python-stack-to-the-browser/

**Comment by marcofavorito** [comment]
see https://github.com/fetchai/agents-aea/pull/813#issuecomment-589223058
