### ISSUE TITLE
Compliance with PEP 518

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#747]
**Is your feature request related to a problem? Please describe.**

The project is not compliant with [PEP 518](https://www.python.org/dev/peps/pep-0518/)

**Describe the solution you'd like**

Being compliant. That is, specifying the `pyproject.toml` file to store the build system dependencies.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by marcofavorito** [comment]
Given that:
- we are using `setuptools` as the build system
- the support of `pyproject.toml` specification for `setuptools` is under discussion: https://github.com/pypa/setuptools/issues/1688

I see two alternatives:
- leave everything as it is now
- change the build system (e.g. poetry)

**Comment by DavidMinarsch** [comment]
Ok thanks, so leave everything as is for now.

**Comment by sinoroc** [comment]
For info, I believe a `pyproject.toml` file like the following should be enough to make a _setuptools_-based project comply with PEP518:

```
[build-system]
requires = ['setuptools']
build_backend = setuptools.build_meta
```
without having to make changes to the `setup.py` and `setup.cfg` files.

Example: https://github.com/pypa/setuptools/blob/c0154f47121ca107095eb52ca1462c23b7457045/pyproject.toml
