### ISSUE TITLE
"aea config set" unexpected behaviour with bad value and type args

### ISSUE THREAD

**Issue by panasevychol** [fetchai/agents-aea#758]
**Describe the bug**
When running `aea config set agent.version bad --type=float` we see no output and value isn't set.

**To Reproduce**
1. `aea create my_first_agent`
2. `cd my_first_agent`
3. `aea config set agent.version bad --type=float`

**Expected behavior**
Error message. Those lines supposed to handle the case:
`aea.cli.config:249`
```
except ValueError:
        logger.error("Cannot convert {} to type {}".format(value, type_))
```
But it is not.

**Comment by marcofavorito** [comment]
I tried to reproduce the bug, but I get the right output:
```
error: Cannot convert bad to type <class 'float'>
```

You can reproduce in this way:
```
virtualenv issue_758
source issue_758/bin/activate
pip install "aea[all]"
aea create agent_758
cd agent_758
aea config set agent.version bad --type=float
```

I also get the same message error when I run it in the `aea-develop` image. To reproduce:
```
./develop-image/scripts/docker-build.sh
./develop-image/scripts/docker-run.sh
```
