### ISSUE TITLE
Tests for launch command failing.

### ISSUE THREAD

**Issue by Totoual** [fetchai/agents-aea#877]
**Describe the bug**
- Pulled release/v0.3
- Run the tests with `make test`

Received the following errors:

```
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
```
/agents-aea/tests/test_cli/test_launch.py:154: ProcessLookupError
/agents-aea/tests/test_cli/test_launch.py:81: ProcessLookupError

**Comment by DavidMinarsch** [comment]
Seems to be discussed here @marcofavorito: 
- https://turtlemonvh.github.io/python-multiprocessing-and-corefoundation-libraries.html
- https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
