### ISSUE TITLE
Customize what should be part of the fingerprint and what not.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#893]
**Is your feature request related to a problem? Please describe.**

In a generic skill component there could be many types of files. We have to decide what must be included in the fingerprint computation and what not.

E.g. should `.json` be included or excluded? Probably it depends on the context, although usually `json` files are used for configuration. 
What about the `.db` file in `weather_station`?

**Describe the solution you'd like**

A list of "ignore" patterns in the config file? Or a convention.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidMinarsch** [comment]
I think an ignore pattern in the config file is more realistic. In addition all `*.py` must be hashed by convention.
