### ISSUE TITLE
Make clear in the documentation the workflow for `aea scaffold`.

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#904]
**Is your feature request related to a problem? Please describe.**

As stated here: https://github.com/fetchai/agents-aea/pull/879#discussion_r387526243
after `aea scaffold <item_type> <item_name>`, the user has to fingerprint the package
whenever it changes it in order to run the agent or doing any other action
that requires the fingerprints.

**Describe the solution you'd like**

Describe this issue in the docs.

**Describe alternatives you've considered**
That suggests we could require automatic generation of fingerprints for custom packages (so also for the scaffolded ones).

**Additional context**

**Comment by DavidMinarsch** [comment]
I think automatic generation has its downsides. It obscures the fingerprint usage to the end user when what we want is to make this something the end user cares about.
