### ISSUE TITLE
Improve `ConnectionStatus` to include many other cases

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#922]
**Is your feature request related to a problem? Please describe.**

Currently, a connection can be in status connected or not connected.
However, there are other cases, e.g.:
1. not connected
2. trying to connect
3. attempt to connect failed
4. attempt to connect timed out
5. connection established
6. connection lost

**Describe the solution you'd like**

Trying to find a good trade-off between richness of the enumeration and easiness of usage.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidMinarsch** [comment]
After discussion we settled on: “disconnected”, “connecting”, “connected”, “disconnecting” states
