### ISSUE TITLE
Improve JSON schema definition for `fingerprint`

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#935]
**Is your feature request related to a problem? Please describe.**

Fingerprint is defined as `object` in `definitions.json` schema:
https://github.com/fetchai/agents-aea/blob/release/v0.3/aea/configurations/schemas/definitions.json#L45-L47

However, it should be a mapping from file names to fingerprint. Although we can't check at load time the consistency of the fingerprints (but only when we match the content of the configuration with the content of the package), we can still filter out badly formatted fingerprints.

**Describe the solution you'd like**
Improve the fingerprint jsonschema definition.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidMinarsch** [comment]
Low priority and caught later at load time anyway
