### ISSUE TITLE
Include option in `aea launch` for `--connections` option for subprocesses

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#952]
**Is your feature request related to a problem? Please describe.**
Currently. `aea launch` will use the default connection for every agent subprocess.

**Describe the solution you'd like**
Find a way to forward a custom connection option, instead of editing the `default_connection` in the `aea-config.yaml`.

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidMinarsch** [comment]
I think the best way to do it is to change `default_connection` to `default_connections`, a list. If multiple agents are run it will be cumbersome to list the connections for each agent in the cli command.
