### ISSUE TITLE
Revise component dependencies assumptions

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#960]
**Is your feature request related to a problem? Please describe.**

Currently, the following holds:
- A protocol cannot depend on other protocols/connections/skills/contracts
- A connection can depend on protocols, but not on other connections/skills/contracts
- A skill can depend on protocols/connections/contracts, but not on other skills
- A contract cannot depend on other protocols/connections/skills/contracts

Also, an agent can depend on any component, but not on other agents.

**Describe the solution you'd like**

Relax these assumptions and make them more generic: a package can depend on any other package.

**Describe alternatives you've considered**

Maybe keep some constraints (e.g. protocols and contracts cannot have dependencies.)

**Additional context**

**Comment by DavidMinarsch** [comment]
It makes sense to have the following dependencies:
- A protocol cannot depend on other protocols/connections/skills/contracts [nothing changes]
- A connection can depend on protocols, but not on other connections/skills/contracts [nothing changes]
- A skill can depend on contracts/protocols but not on other skills [add possibility for other skill dependence]
- A contract cannot depend on other protocols/connections/skills/contracts [nothing changes]

I do not think there is a benefit in relaxing these dependencies further. It could have very unintended side effects.

**Comment by DavidMinarsch** [comment]
This should also address the fact that we need to be able to define dependency on dm from skills

**Comment by marcofavorito** [comment]
PR #1403 introduces the risk of circular dependency. 
Examples:

- `skill_a` depends on `skill_a` (self-loop)
- `skill_a` depends on `skill_b` that depends on `skill_a`. (cycle of length 2)
- `skill_a` depends on `skill_b` that depends on `skill_c` that depends on `skill_a`. (cycle of length 3)

The recursive call to `aea add` is able to handle it, because if a dependency is missing it will retrieve it from the (local?) registry

The call to `AEABuilder.add_component` won't work because it requires the dependencies to be already added, and in the case of a cycle, this can't work because in the dependency DAG there's no leaf node to start with.
