### ISSUE TITLE
Support a command analogous to 'go get' to get AEA packages published on GitHub

### ISSUE THREAD

**Issue by marcofavorito** [fetchai/agents-aea#992]
**Is your feature request related to a problem? Please describe.**
A nice feature of the Golang stack is that you can get Go packages published on GitHub with:
```go get <url-to-repo>```

We could have something similar to the AEA framework. 

**Describe the solution you'd like**
Extend the `aea add` command, or create a new one like `aea get`, to get agent components from GitHub. 
This could also be used to get AEA projects, not only components, from GitHub/Bitbucket etc.

**Describe alternatives you've considered**
Call it `aea pull`?

**Additional context**
https://golang.org/pkg/cmd/go/internal/get/

**Comment by DavidMinarsch** [comment]
Our current CLI has quite a comprehensive set of commands covering a wide range of use cases. In particular, it is already possible to fetch entire aea projects with `aea fetch`. The idea with the aea-config files and aea fetch command was to be able to specify an entire aea with a single config file. This is a neat approach and currently already supported. The suggested addition of GH as a registry does introduce new complexities, for instance if repos are removed the paths break. I prefer the approach we take with registry + full IPFS integration. The registry is already IPFS capable and the CLI will soon be too.

**Comment by DavidMinarsch** [comment]
Closing; consider the matter settled.
